### ISSUE TITLE
Braces printed on startup

### ISSUE THREAD

**Issue by offdroid** [simrat39/rust-tools.nvim#10]
On startup, rust-tools prints a set of braces `{}`. It seems like a debug statement that is not of any use for regular users (as far as I can tell) and should probably be removed.

https://github.com/simrat39/rust-tools.nvim/blob/9ab7481baedfdc423b190b0aeb95f0b3d463c5ee/lua/rust-tools.lua#L23-L25

**Comment by simrat39** [comment]
Thanks for the report, this seems to be something i missed, ill push a fix in some time
