### ISSUE TITLE
switching between RA messages

### ISSUE THREAD

**Issue by adsick** [simrat39/rust-tools.nvim#100]
![image](https://user-images.githubusercontent.com/24528839/144720214-ad69f549-f910-4f43-b456-b6bde0e49229.png)
how do I browse those RA outputs? it only shows one line at a time and I want to see them all.

**Comment by simrat39** [comment]
vim.diagnostic.setqflist() then :copen should work, see :h vim.diagnostic

**Comment by adsick** [comment]
unintuitive(

**Comment by simrat39** [comment]
you can use https://github.com/folke/trouble.nvim as well

**Comment by simrat39** [comment]
vim.diagnostic.open_float() on the current line also would show all the diagnostics
