### ISSUE TITLE
[deprecated] Use of deprecated `lsp` api in `rust-tools/code_action_group.lua`

### ISSUE THREAD

**Issue by kunzaatko** [simrat39/rust-tools.nvim#108]
`vim.lsp.diagnostic.get_line_diagnostics()` is now deprecated in favour of `vim.diagnostic.get`. There is a help page on deprecation `:h deprecated`.

**Comment by kunzaatko** [comment]
You can assign me to this issue, however I will have time for it in about 2 weeks at the earliest.

**Comment by kunzaatko** [comment]
akinsho/bufferline.nvim#272

**Comment by simrat39** [comment]
But vim.diagnostic.get can have errors from other places as well, while I think the lsp only cares for its own errors? (I think). Atleast core still uses vim.lsp.diagnostic... https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/buf.lua#L595

**Comment by kunzaatko** [comment]
Yeah. I guess that it is OK. I was mistaken to think that you should not use this anymore.
