### ISSUE TITLE
Renaming variables in tests causes to rename only the declaration

### ISSUE THREAD

**Issue by augustocdias** [simrat39/rust-tools.nvim#109]
I don't know if this is an issue with neovim or with rust-tools. If it is with neovim I'll open the issue on their repo.

When I call `vim.lsp.buf.rename()` on a variable inside a test in rust it is not renaming the references but rather just the declaration.

In my setup, I tried to rename the `req` variable in this file: https://github.com/actix/actix-web/blob/master/src/test/test_request.rs#L428

and it changed only the declaration and not the reference(s).

**Comment by augustocdias** [comment]
It happens with the following minimal config:

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup({
        {
            'wbthomason/packer.nvim',
            'neovim/nvim-lspconfig',
            'simrat39/rust-tools.nvim',
            -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    })
end
_G.load_config = function()
    require('rust-tools').setup({})
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path })
end
load_plugins()
require('packer').sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by simrat39** [comment]
Sounds like a rust-analyzer issue, does it happen with vs-code?

**Comment by augustocdias** [comment]
Yeah I tried in vscode and It does not happen.

**Comment by simrat39** [comment]
Then its probably a neovim issue. If you can, try replicating this with lspconfig

Sorry i've been very busy so I couldn't get back to it faster

**Comment by augustocdias** [comment]
I've managed to reproduce it in VSCode, though inconsistently whereas in nvim it always happens... I opened an issue in rust analyser as it seems the issue is there
