### ISSUE TITLE
Influence of get_root_dir on startup time.

### ISSUE THREAD

**Issue by hgaiser** [simrat39/rust-tools.nvim#112]
I've been playing around with rust-tools.nvim, trying to see why my startuptime for rust projects is significantly higher than for example with cpp projects. It seems that the invocation to `cargo` to get the root dir is the culprit.

Without any modifications I get the following:

```
$ hyperfine "nvim src/error.rs -c qall"    
Benchmark 1: nvim src/error.rs -c qall
  Time (mean ± σ):     294.8 ms ±  42.0 ms    [User: 224.9 ms, System: 62.9 ms]
  Range (min … max):   213.5 ms … 362.1 ms    10 runs
```

If I change [these](https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools.lua#L135-L163) lines with:

```lua
local function get_root_dir(filename)
	local fname = filename or vim.api.nvim_buf_get_name(0)
	local cargo_crate_dir = lspconfig_utils.root_pattern("Cargo.toml")(fname)
	return cargo_crate_dir
		or lspconfig_utils.root_pattern("rust-project.json")(fname)
		or lspconfig_utils.find_git_ancestor(fname)
end
```

I get the following:

```
$ hyperfine "nvim src/error.rs -c qall"
Benchmark 1: nvim src/error.rs -c qall
  Time (mean ± σ):     165.2 ms ±  10.7 ms    [User: 114.9 ms, System: 44.5 ms]
  Range (min … max):   139.8 ms … 180.1 ms    16 runs
```

That's a pretty significant ~130msec difference. I am aware that `lspconfig` is doing [something similar](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/rust_analyzer.lua#L17-L54) for getting the root dir.

Is there some way we can work around this issue? Alternatively, would it be possible to override `root_dir`, like in `lspconfig`, so that I can define a simpler method for getting the root dir? It will likely fail on standalone files then, but I'm okay with that.

Something else I noticed while debugging is that the `get_root_dir` function seems to be called twice, once by [rust-tools](https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools.lua#L172) and once by [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/22b21bc000a8320675ea10f4f50f1bbd48d09ff2/lua/lspconfig/configs.lua#L213). For an 'expensive' function like this, maybe it is an idea to cache the results?

**Comment by simrat39** [comment]
Yeah I will make it configurable.

As for caching, I don't think we should do that because lspconfig might have to use that function when the cwd changes, i'm not too sure about that actually

**Comment by simrat39** [comment]
Also I could add an option to check for standalone files on start, so if you don't use that feature you can skip the overhead

**Comment by simrat39** [comment]
Should be faster now, with server.standalone = false

**Comment by hgaiser** [comment]
Thank you for the update, much appreciated! My startuptime is reduced from ~480msec to ~140msec by adding this configuration:

```lua
		standalone = false,
		root_dir = require('lspconfig').util.find_git_ancestor,
```
