### ISSUE TITLE
Weird glitches involving brackets

### ISSUE THREAD

**Issue by ruffson** [simrat39/rust-tools.nvim#117]
Sorry for the title, I did not know how else to phrase it. I recently tried out rust-tools following shark-for-arms' guide.
My init is [here](https://github.com/ruffson/dotfiles/blob/master/init.vim).

So the problem occurs relatively often. What happens is, when I want to change brackets like in the gif below, it results in the following problems:
- Wrong brackets are added
- Characters are overidden.

First I thought this is a bug in  the `auto-pairs` plugin, but removing it and re-trying the example below did not help. Only removing this plugin stopped the behaviour.

A GIF showing the problem (notice how the _e_ of _rename_ is missing after the brackets are added. All I did is trying to add a `{` after the last `)`. Instead of the `{` it adds `){}}` with the curser in the middle. Weird, especially the missing charactters of the function call.
![matching pairs_3](https://user-images.githubusercontent.com/1185812/147865513-b55e3401-0cad-48d9-a7e1-b7dbc245ebe3.gif)

Neovim version 0.6.0, on Fedora 35.

**Comment by simrat39** [comment]
Uhm this is not a rust-tools issue, i'm not too sure why this happens. Does this happen in other filetypes as well?

**Comment by ruffson** [comment]
I understand that this is really weird and seems to be no problem with rust-tools but I just tested with a minimal config from [here](https://raw.githubusercontent.com/sharksforarms/neovim-rust/master/neovim-init-lsp-cmp-rust-tools.vim) with the following simple code snippet (just a single rust file no cargo):

```
  use std::fs;
   
  fn main() {
      println!("Test");
      let _ = fs::rename("foo", "bar");
  }
```
Doing exactly what I did above triggers weird behavior. And when I remove rust-tools and clean plug-vim, the problem does not exist.

Is this a problem with neovim in combination with rust-tools?

rust-analyzer version btw:
```
rust-analyzer d9b2291f5 2021-11-29 stable
```
But newer version that I just updated to has the same problem:
```
rust-analyzer 0f8c96c92 2022-01-10 stable
```

**Comment by simrat39** [comment]
Honestly I have no clue, if possible could you provide a minimal init.lua to reproduce? Thanks

Sorry for the late reply

**Comment by zaeleus** [comment]
I have this issue.

I narrowed it down to the `inlay_hints.show_parameter_hints` option in rust-tools.nvim. Setting it to `false` causes the character shifting.

As a workaround, set the option to `true` (the default), but, of course, this enables the hints.

**Comment by ruffson** [comment]
> I have this issue.
> 
> I narrowed it down to the `inlay_hints.show_parameter_hints` option in rust-tools.nvim. Setting it to `false` causes the character shifting.
> 
> As a workaround, set the option to `true` (the default), but, of course, this enables the hints.

That did it, thank you so much for investigating, I would have probably abandoned the plugin due to time constraints.

**Comment by FL33TW00D** [comment]
Still having the same issue - can confirm that `inlay_hints.show_parameter_hints` to `false` resolves the issue - but isn't optimal for those of us that don't want parameter hints.

**Comment by simrat39** [comment]
I still can't replicate it, but a rewrite of the inlay hints code is gonna come soon and that should hopefully fix it

**Comment by geoboom** [comment]
I'm having the same issue:
![image](https://user-images.githubusercontent.com/13282914/154677131-f94988d3-d1b4-41e7-a434-4c5b1bd43e34.png)

**Comment by simrat39** [comment]
Should be fixed now, let me know if it isn;t, I'll close the issue tomorrow
