### ISSUE TITLE
Question: real-time updating of diags and inlay hints?

### ISSUE THREAD

**Issue by walkert** [simrat39/rust-tools.nvim#119]
Hi there,

I've been experimenting with the rust-tools plugin and wondering about the update behaviour for diagnostics and inlay hints.

Some diagnostics appear immediately - for example if I leave off a semicolon I get an immediate update with `E Syntax Error: expected SEMICOLON`. If I add it back - the diag disappears. However, if I write `let x = 30;`, it's only when I write the buffer that I get the 'unused variable' warning (perhaps because that's from clippy)?

Similar question for inlay hints. By default, if I add the above line, I'll only get the type hint when I write the buffer. If I switch to enabling `only_current_line` and set `only_current_line_autocmd = "CursorHold,CursorMovedI"` then I get a real-time update (as documented). Is there any way to enable this "update without writing the buffer" behaviour for all lines so that it happens immediately (or when switching from insert to command mode)?

Thanks!

**Comment by simrat39** [comment]
The first issue is not related to rust-tools, probably a rust-analyzer/clippy/lspconfig/nvim issue.
The second issue we can add a config for

Sorry i've been very busy so I couldn't get back to it faster

**Comment by walkert** [comment]
Thanks for the info. And no worries about the delay - I appreciate the response.

**Comment by mjlbach** [comment]
> The first issue is not related to rust-tools, probably a rust-analyzer/clippy/lspconfig/nvim issue

It's a rust-analyzer "feature", it only calls cargo check on each save for performance reasons. It's not a bug in neovim/lspconfig.

**Comment by pinhead-domi** [comment]
> It's a rust-analyzer "feature", it only calls cargo check on each save for performance reasons. It's not a bug in neovim/lspconfig.

Is there a known way to configure it in order to get real-time diagnostics?

**Comment by mjlbach** [comment]
Not apart from filing a series of not-inconsequential PRs to rust analyzer.

**Comment by walkert** [comment]
Closing. Thanks.
