### ISSUE TITLE
customise float window borders?

### ISSUE THREAD

**Issue by elianiva** [simrat39/rust-tools.nvim#12]
Hi there! This plugin is *super* cool, especially those inlay hints and hover action.
I have an issue though. I noticed that the border for the hover window is hardcoded, which isn't what I want.
I'd like to be able to change it. Here's what it currently has compared to how I want it to look.

- Default
  ![image](https://user-images.githubusercontent.com/51877647/116962807-445cb200-acd1-11eb-9528-a51cd24519ec.png)
  
- Mine
  ![image](https://user-images.githubusercontent.com/51877647/116962875-7c63f500-acd1-11eb-82dd-b89d8765607b.png)
  
Thanks in advance!

**Comment by simrat39** [comment]
For some reason nvim_open_win adds top and bottom padding to the border with "single" and "double" options, I'll look more into it tomorrow. I'm not sure how to get rid of the padding right now

**Comment by elianiva** [comment]
the padding is fine -- I just want to pass my own border instead of using the builtin/hardcoded ones.

**Comment by simrat39** [comment]
2e615d4a039d2fc580479a5e512330527d151d3f 
let me know if it works fine for you

**Comment by elianiva** [comment]
works great, thank you!
