### ISSUE TITLE
Feature request - Doc comments syntax highlighting

### ISSUE THREAD

**Issue by demfabris** [simrat39/rust-tools.nvim#123]
Not sure this is the right place to ask this but in CoC we had syntax highlighted `///` and `//!` comment sections.
This feature was useful to write doc tests with syntax highlighting

**Comment by simrat39** [comment]
This is a neovim related issue, COC probably used semantic highlighting support for which (afaik) is not in neovim yet

**Comment by ModProg** [comment]
>  which (afaik) is not in neovim yet

Hopefully this will get us there: https://github.com/neovim/neovim/pull/15723

**Comment by simrat39** [comment]
Yup, that PR will make it work most probably
