### ISSUE TITLE
Inline Inlay Hints

### ISSUE THREAD

**Issue by srilman** [simrat39/rust-tools.nvim#126]
Hi! First of all, thanks for this great extension. I've been looking for a way to take advantage of all of rust-analyzer's features in NeoVim, and this looks like just what I need. However, I noticed one difference with how inlay hints are displayed in NeoVim in comparison to VSCode.

In VSCode, hints are integrated within the lines like so:
<img width="726" alt="Screen Shot 2022-01-12 at 4 55 01 PM" src="https://user-images.githubusercontent.com/17444967/149229990-8f061b62-9d88-4b7c-ae44-cb7462db33e2.png">

On the other hand, NeoVim appends hints to the end of the line like os:
<img width="903" alt="Screen Shot 2022-01-12 at 4 54 30 PM" src="https://user-images.githubusercontent.com/17444967/149230192-ee4f2b25-e512-494d-a328-e4ee8522580e.png">

Is it currently possible to display hints like VSCode does in NeoVim? If not, is it possible to include such a feature? What prerequisites are necessary to implement this? I'd be happy to help implement it; its much easier to read parameter and type hints when they're inlined rather than appended at the end of lines, especially for more complex situations!

**Comment by srilman** [comment]
After some research, I found out that this requires changes to Neovim. Closing for now until appending inline virtual text is supported.

**Comment by karoofish** [comment]
As inline virtual text has arrived in Neovim, would this be now possible?
