### ISSUE TITLE
Vim commands are no longer defined

### ISSUE THREAD

**Issue by krady21** [simrat39/rust-tools.nvim#13]
Since the last refactor, I am no longer able to call the vim commands defined by rust-tools.nvim (RustRunnables, RustSetInlayHints, etc). I've tried with both my personal config and the one shown in the README. Mine looks like this:
```
require('rust-tools').setup {
  tools = {
    autoSetHints = false,
    hover_with_actions = false,
    runnables = { use_telescope = false },
  },
}
```
Am I doing something wrong or am I now supposed to define my own commands for the lua functions?

**Comment by simrat39** [comment]
> Since the last refactor, I am no longer able to call the vim commands defined by rust-tools.nvim (RustRunnables, RustSetInlayHints, etc). I've tried with both my personal config and the one shown in the README. Mine looks like this:
> 
> ```
> require('rust-tools').setup {
>   tools = {
>     autoSetHints = false,
>     hover_with_actions = false,
>     runnables = { use_telescope = false },
>   },
> }
> ```
> 
> Am I doing something wrong or am I now supposed to define my own commands for the lua functions?

The commands seem to work fine for me. FYI the commands are only registered when the LSP is registered, so make sure rust-analyzer is running before trying the commands

**Comment by krady21** [comment]
I think i found the culprit. The commands appear only when `require('rust-tools').setup(opts)` is done after the on_attach setup for lspconfig.

**Comment by simrat39** [comment]
Are you by any chance setting up lspconfig for rust analyser yourself? This plugin does that automatically so that might be causing some mismatch.

**Comment by krady21** [comment]
Nope. I am using the common config suggested in the lspconfig wiki:
```
local nvim_lsp = require('lspconfig')
local servers = { "clangd", "rust_analyzer", "pyright", "texlab", "hls", "gopls" }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup { on_attach = on_attach }
end
```

**Comment by simrat39** [comment]
> I think i found the culprit. The commands appear only when `require('rust-tools').setup(opts)` is done after the on_attach setup for lspconfig. The new problem is that if I do this, the lspconfig rust-analyzer setup seems to break (I no longer get the lsp mappings set in the on_attach function) sob

BTW you can still override rust-analyzer's on attach by passing it into the setup function, see the readme for instructions. You **DONT** have to setup rust-analyzer yourself, this plugin will do it for you.

I'll close the issue but feel free to open it again if you have any issues.

**Comment by krady21** [comment]
It all works well now. Thanks for the help!

**Comment by lovesegfault** [comment]
I'm hitting this too, but I don't really understand the solution.

I have my mapings defined on `on_attach`, and when I `require("rust-tools")` it makes all my mappings disappear. This is my LSP config: https://github.com/lovesegfault/nix-config/blob/neovim-0.5/users/bemeurer/core/neovim/lua/lovesegfault/lsp.lua

How can I enable rust-tools without it touching the rest of my config?
