### ISSUE TITLE
Inlay functions hints missing

### ISSUE THREAD

**Issue by Sokom141** [simrat39/rust-tools.nvim#130]
Hi, some inline hints are missing compared to the vscode counterpart. 
Specifically they are missing in the function calls, I attach here a screenshot to demonstrate the difference:
![image](https://user-images.githubusercontent.com/7696833/150680348-3c714f0a-4dd7-4b14-9931-2bb59888f2d2.png)

I feel like these are really useful when calling functions defined elsewhere.
Is it feasible to have something like that with this plugin as well?
Thanks

**Comment by simrat39** [comment]
![image](https://user-images.githubusercontent.com/37233846/150715241-78486c74-a812-46ef-9532-62b54450795b.png)
Seems to work fine for me, are you saving the file? and what's your config like?

**Comment by Sokom141** [comment]
Hi, thanks for the fast response.
I've actually made a mistake in my config and wasn't aware of it. I have now correctly set the parameter for functions hint and it's now working correctly. 
Sorry for the mistake.

Still there is a subpar syntax highlighting compared to vscode, especially in variables inside strings format, constants and namespaces. 
I wonder if this is a current limitation of lsp in neovim or I'm doing something wrong again.
This is my current config: https://gist.github.com/Sokom141/fe39b44ee247db6b66953649e2bb5e97

Thanks for your time
