### ISSUE TITLE
in some case jump by tag (ctrl+]) to field declaration not working

### ISSUE THREAD

**Issue by xakep71k** [simrat39/rust-tools.nvim#134]
Hello!
Thank you for awesome neovim plugin for rust!
It seems I found a bug.
Here is example code https://github.com/xakep71k/bug_rust_nvim/blob/master/src/main.rs
Begining at line 75

> ...
> "division": self.division,
> ...

I cannot jum to declaration of division field with ctrl+]. It does not work for all fields below 75 line. But lines above works fine. This problem is not repeatable in vscode.
Here is my config for neovim:
> local nvim_lsp = require'lspconfig'
>
> 
> local rust_opts = {
>     tools = { -- rust-tools options
>         autoSetHints = true,
>         hover_with_actions = true,
>         inlay_hints = {
>             show_parameter_hints = false,
>             parameter_hints_prefix = "",
>             other_hints_prefix = "",
>         },
>     },
> 
>     server = {
>         settings = {
>             ["rust-analyzer"] = {
>                 -- enable clippy on save
>                 checkOnSave = {
>                     command = "clippy"
>                 },
>             }
>         }
>     },
> }
> 
> require('rust-tools').setup(rust_opts)
> 
> vim.cmd('autocmd BufWritePre *.rs lua vim.lsp.buf.formatting_sync(nil, 200)')
>

**Comment by simrat39** [comment]
Not sure if this is related to rust-tools, can you reproduce this with plain lspconfig rust analyzer?

**Comment by xakep71k** [comment]
@simrat39 I would try but I do not know how to setup plain lspconfig rust analyzer. Could you please suggest how to do that?

**Comment by xakep71k** [comment]
I have tried plain rust analyzer and it seems you are right that it is not related to rust-tools
