### ISSUE TITLE
No inlay hints shown and commands missing

### ISSUE THREAD

**Issue by kirillbobyrev** [simrat39/rust-tools.nvim#136]
HI! I have a hard time setting up inlay hints: when I run Neovim, only a fraction of commands are available and no inlay hints are shown at all.

Here are the only commands prefixed with `:Rust` that Neovim recognizes (nothing Inlay Hints-related here!):

![InlayHints](https://user-images.githubusercontent.com/3352968/151543933-e1912f8b-d1ab-444a-9e68-e8e4e307f729.jpeg)

The inlay hints appear **only** when I manually run `:lua require('rust-tools.inlay_hints').toggle_inlay_hints()` from Neovim but that's the only way to make it work.

Is there anything I did incorrectly in my setup?

### My plugin setup

I use a fairly minimalistic plugin setup that is mirroring suggested config options in rust-tools.nvim's README, so it should be working as expected.

```lua
  use {
    'neovim/nvim-lspconfig',
    config = function()
      require('lspconfig').clangd.setup {}
      require('lspconfig').rust_analyzer.setup {}
    end,
  }
  -- ...
  use {
    'simrat39/rust-tools.nvim',
    requires = {
      'neovim/nvim-lspconfig',
    },
    config = function()
      require('rust-tools').setup()
      require('rust-tools.inlay_hints').set_inlay_hints()
    end,
  }
```

### Full Neovim plugin setup

https://github.com/kirillbobyrev/dotfiles/blob/19aa0c2ebb9cfe5c848b6c1b5f4050bd0c5c4403/.config/nvim/lua/plugins.lua

### rust-tools.nvim version

`HEAD`, i.e. https://github.com/simrat39/rust-tools.nvim/commit/876089969aa8ccf8784039f7d6e6b4cab6d4a2b1

### Neovim version

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by kirillbobyrev** [comment]
Nevermind, somehow the Inlay Hints are back.

**Comment by officiallyaninja** [comment]
for anyone who has this issue in the future, make sure you haven't setup rust_analzyer using lsp config.  
> require('lspconfig').rust_analyzer.setup {}

this will cause some conflict causing certain commands to not be available
