### ISSUE TITLE
Errors for MoveItem

### ISSUE THREAD

**Issue by theduke** [simrat39/rust-tools.nvim#14]
I'm getting an error for the `MoveItem` commands:

`Error executing vim.schedule lua callback: ...unwrapped-master/share/nvim/runtime/lua/vim/lsp/util.lua:461: attempt to index local 'text_document' (a nil value)`

Neovim master from 3 days ago.

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/commit/6f92ba636c06069592c64f85888b452da7e81cfd 
This should fix it

**Comment by theduke** [comment]
Oddly enough, with the current master I now see a lot fewer commands.

They still work with lua calls like `:lua require'rust-tools.parent_module'.parent_module()`, but are not in the command list anymore.

![2021-05-17T12:11:06+02:00](https://user-images.githubusercontent.com/241621/118472471-66eec200-b6f8-11eb-8439-22906c53fc1c.png)

**Comment by theduke** [comment]
On the plus side, the move commands now work (with lua calls).

**Comment by simrat39** [comment]
Are you by any chance setting up lspconfig for rust analyser yourself? This plugin does that automatically so that might be causing some mismatch.

**Comment by theduke** [comment]
Ah yeah, that was it, I forgot to comment out the custom rust-analyzer config.

Weird that it was working before.

All good now, thanks!

**Comment by theduke** [comment]
@simrat39 this is not really related, but do you know of a way to inject things like `Move Item Down` into the actions menu , but only for Rust items?

Is there some rust-analyzer config for this, or can it be done manually? 

(I'm using https://github.com/glepnir/lspsaga.nvim )

**Comment by simrat39** [comment]
@theduke I don't think it's possible right now, but won't be that hard to implement if LspSaga allowed injecting code actions
