### ISSUE TITLE
lldb-vscode: no such file or directory

### ISSUE THREAD

**Issue by Kangaxx-0** [simrat39/rust-tools.nvim#141]
I am new to Rust, I followed the steps to set up debug, but ended up with the below error, did i miss anything or how could i set it up correctly?

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/85712372/153786194-5dc58a9d-f78f-4592-8b82-fd470a6fed73.png">

**rust-tools config**
<img width="872" alt="image" src="https://user-images.githubusercontent.com/85712372/153786354-779d8e14-4de9-4cab-bf71-1ccbf0f0b276.png">

**Run codelldb** 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/85712372/153786376-4476f5c0-14a3-48d1-bd0e-fe0764b3290e.png">

**Comment by simrat39** [comment]
Looks like dap is looking for lldb-vscode. How are you starting your debugging? rust-tools only supports debugging from the hover actions window, you are responsible for setting up normal dap debugging

**Comment by abosnjakovic** [comment]
confirming I start from hover actions and still face the above issue with the same config described above

![image](https://user-images.githubusercontent.com/5321192/156072141-596a6caf-876e-47ee-83bb-4de1233ee66b.png)


![image](https://user-images.githubusercontent.com/5321192/156072012-ba3b0b72-c0e7-4a0f-aa02-17d84506268b.png)

**Comment by Kangaxx-0** [comment]
I followed this [link](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(via--codelldb)) to get everything working

**Comment by leoperegrino** [comment]
> Looks like dap is looking for lldb-vscode. How are you starting your debugging? rust-tools only supports debugging from the hover actions window, you are responsible for setting up normal dap debugging

I'm using the hover window to start and I'm getting the same error: 

```
Error executing vim.schedule lua callback: ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:385: ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:
1237: Error running lldb-vscode: ENOENT: no such file or directory
stack traceback:
        [C]: in function 'trigger_run'
        ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:385: in function 'run'
        ...pack/packer/start/rust-tools.nvim/lua/rust-tools/dap.lua:103: in function <...pack/packer/start/rust-tools.nvim/lua/rust-tools/dap.lua:74>
```

Even though I have configured rust tools to point to `codelldb`

```
	opts.dap = {
		adapter = require("rust-tools.dap").get_codelldb_adapter(
			"/usr/bin/codelldb",
			"/usr/lib/codelldb/lldb/lib/liblldb.so"
		)
	}

	opts.settings = {
		["rust-analyzer"] = {
			inlayHints = { locationLinks = false },
		}
	}

	rust_tools.setup { server = opts }
```

Running `RustDebuggables` give me the same result.

**Comment by leoperegrino** [comment]
Ok, nevermind. I just realized that I was passing `rust_tools.setup { server = opts }` when it should've been `rust_tools.setup(opts)`
