### ISSUE TITLE
Autocompletion after a period always suggests snippets over methods, regardless of configuration

### ISSUE THREAD

**Issue by monomadic** [simrat39/rust-tools.nvim#142]
I have struggled with this for several hours now and can't find a solution - I've even tried creating a fresh `init.lua` - I assume this is the default behaviour of `rust-tools`.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/129359/154732691-3e74d35b-0789-440f-beb2-c1c2a440a5aa.png">

Essentially, autocomplete works just fine, but finishing any completion followed by a `.` will always prioritise snippets first. I honestly could not care about snippets at all and need to see what methods and properties are included in the object before it (partially autocomplete is for introspection for me) and then tab-completing those methods.

I have this working with other languages, it seems to be restricted to `rust-tools` (I could be wrong). Setting `sources` passed to the options for `cmp` is not respected within rust projects. Neither is `priority`. It seems rust-tools ignores them.

I've tried this with the default setup on the examples page also and an empty setup {}.

Here's another example of why this breaks:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/129359/154734191-c0f9ebe2-93f2-48e1-9704-431262c9946d.png">

Selecting any of those snippets is invalid anyway for this code situation.

Any help would be greatly appreciated, thank you!

**Comment by monomadic** [comment]
Update: I solved this by adding the following to my config:

```lua
local compare = require('cmp.config.compare')

cmp.setup {
    ...
  sorting = {
      priority_weight = 2,
      comparators = {
        compare.score,
      },
    },
}
```

Strangely, other plugins always worked with default sorting - does rust-tools override this somewhere? It's a very unintuitive default..

**Comment by simrat39** [comment]
Nope we don't override this anywhere, its all nvim-cmp and rust-analyzer.
Anyways closing because you fixed it
