### ISSUE TITLE
How to Configure Standalone server and Rust analyzer

### ISSUE THREAD

**Issue by goldcoders** [simrat39/rust-tools.nvim#145]
Is there anyone that setup their vim lua 

that allows you to switch on rust-analyzer and rust-analyzer-standalone

rust analyzer is for a rust project with cargo.toml inside the directory

while the standalone is just pure .rs file (this is good when you only want to test small chunk of code)

the documentation seems to be bit odd,
it says it support standalone by default

but if you load a rust file only rust-analyzer is loaded by default

Im quite confuse where i would configure this stuff
On lspconfig or rust-tools setup functions

<details>
<summary>This is my current rust tools setup</summary>

```
-- Update this path
local extension_path = vim.env.HOME .. '/.vscode/extensions/vadimcn.vscode-lldb-1.6.10/'
local codelldb_path = extension_path .. 'adapter/codelldb'
local liblldb_path = extension_path .. 'lldb/lib/liblldb.so'

local opts = {
    tools = { -- rust-tools options
        autoSetHints = true,
        hover_with_actions = true,
        inlay_hints = {
            show_parameter_hints = true,
            parameter_hints_prefix = "",
            other_hints_prefix = "",
        },
    },
    -- all the opts to send to nvim-lspconfig
    -- these override the defaults set by rust-tools.nvim
    -- see https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer
    server = {
        -- This doesnt do anything
        standalone = true,

        settings = {
            -- to enable rust-analyzer settings visit:
            -- https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/generated_config.adoc
            ["rust-analyzer"] = {
                -- enable clippy on save
                checkOnSave = {
                    command = "clippy"
                },
            },

        }
    },
    dap = {
        adapter = require('rust-tools.dap').get_codelldb_adapter(codelldb_path, liblldb_path)
    }
}

require('rust-tools').setup(opts)

```
</details>

**Comment by goldcoders** [comment]
I just have no way to implement it with lua, as of now coz Im not that pro ,
but if anyone can share some code or improve what i share above to include solution 
thanks...

But the only work around I can make now is create a remap 
nnoremap to a key that run the command `:execute "RustStartStandaloneServerForBuffer" | LspStop`

I know i wont be using a single rs file most of the time and 
Real projects are manage by cargo, but for copy pasting and experimenting code snippets in rust 
which you dont need to spun a cargo  new project.

I hope someone can find this solution or even yet show much better solution ;)

**Comment by simrat39** [comment]
you don't need to set up lspconfig, only rust-tools. This is probably the cause of your problems.
