### ISSUE TITLE
Hover override should defautl to user defined handler

### ISSUE THREAD

**Issue by etrnal70** [simrat39/rust-tools.nvim#147]
Currently, the only option that can be overridded was border and auto-focus window.

I use this option below to override hover behavior:
```lua
vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, {
  border = "solid",
  max_width = 60,
  max_height = 20,
})

```

but rust-tools seems to ignore those settings.

I think it's better to default to user-defined handler, or maybe give an option to override the handler

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools/config.lua#L22 set this to false in your config, pretty sure that's what you're asking for

**Comment by etrnal70** [comment]
Okay, but what if i also wants to have hover actions ? I think hover actions should extend the existing handler instead of overriding it completely.

**Comment by simrat39** [comment]
Thats not possible afaik, but we should probably give the same customization options in the setup

**Comment by etrnal70** [comment]
I agree with that. I'll see whether i can came up with a PR next week
