### ISSUE TITLE
Loop or previous error loading module 'rust-tools'

### ISSUE THREAD

**Issue by Freyskeyd** [simrat39/rust-tools.nvim#149]
Hello and thanks for this amazing packet that you built !

I open this issue because I was testing `nvchad` recently and I added `rust-tools` as a dependency (in LSP).
As expected it worked pretty well and I end up having a working environment to work. Unless I tried to add some little packet such as `vim-easymotion` (I also did a `PackerSync`).

I though that I fucked up somewhere (and I'm still thinking I have) so I tried to install a fresh and new setup just for `rust-tools`.

I removed:

```bash
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```

After which I cloned and reinstall nvchad + rust-tools, you can take a look here:  https://github.com/Freyskeyd/rust-tools-debug/tree/master/lua/custom

The concrete message is:

```
packer.nvim: Error running config for nvim-lspconfig: .../.config/nvim/lua/custom/plugins/lspconfig.lua:19: loop or previous error loading module 'rust-tools'
```

I have nothing weird in both LSP log and `:checkhealth` or `:message` (just the error above)

Thanks again !

**Comment by david-0609** [comment]
I also run into this issue and the solution of the problem is posted in the NvChad Issues page.
https://github.com/NvChad/NvChad/issues/227
Basically, rust-tools is not lazy loaded but lspconfig is, so rust-tools should wait to load itself until lspconfig is loaded.
