### ISSUE TITLE
Inlay hints are no longer working

### ISSUE THREAD

**Issue by pacak** [simrat39/rust-tools.nvim#152]
After switching from 119 to 120
https://rust-analyzer.github.io/thisweek/2022/03/14/changelog-120.html

**Comment by pacak** [comment]
Probable fix is in #151

**Comment by snaggen** [comment]
Can confirm that inlay hints work with the linked pull request

**Comment by simrat39** [comment]
Should be fixed

**Comment by NasDex** [comment]
I still get this error~
