### ISSUE TITLE
method experimental/inlayHints 

### ISSUE THREAD

**Issue by NasDex** [simrat39/rust-tools.nvim#155]
I still get this error~

```
method experimental/inlayHints is not supported by any of the servers registered for the current buffer
```

I update rust-tools to the newest version, rustc is 1.59.0,  rust-analyzer is the newest too. 

I use LunarVim and this is my lvim config about rust

```
-- Additional Plugins
lvim.plugins = {
  {
    "navarasu/onedark.nvim"
  },
  {"folke/tokyonight.nvim"},
  {
    "folke/trouble.nvim",
    cmd = "TroubleToggle",
  },
  {
    "prettier/vim-prettier",
  },
  {
    "simrat39/symbols-outline.nvim"
  },
--  {
--    "rust-lang/rust.vim"
--  },
  {
    "simrat39/rust-tools.nvim"
  },
}

-- rust-tools
require("rust-tools").setup({
  tools = {
    autoSetHints = true,
    hover_with_actions = true,
    runnables = {
      use_telescope = true,
    },
  },
  server = {
    cmd = { vim.fn.stdpath "data" .. "/lsp_servers/rust/rust-analyzer" },
    on_attach = require("lvim.lsp").common_on_attach,
    on_init = require("lvim.lsp").common_on_init,
  },
})
 
```

**Comment by simrat39** [comment]
What's your rust-analyzer version ?

**Comment by NasDex** [comment]
my rust=analyzer version is `rust-analyzer 5e8515870 2022-03-14 stable`

**Comment by NasDex** [comment]
I update my rust-analyzer version to `rust-analyzer b594f9c44 2022-03-21 stable`, but still get this error.

**Comment by simrat39** [comment]
Are you sure you're using the rust-analyzer binary that you pass in your cmd to get the version?

**Comment by NasDex** [comment]
Yes, i'm sure

**Comment by pca006132** [comment]
I also encountered this issue but was fixed by updating rust-analyzer version. Wondering if it is possible to add a version check for rust-analyzer? I think users with an older version of RA will lost inlay hints after https://github.com/simrat39/rust-tools.nvim/commit/ad22bd03cefac7d6a483f092a36499e9cce6dad5 and have to dig through the log and github issues to understand what is going on...

**Comment by Artturin** [comment]
> have to dig through the log and github issues to understand what is going on...

Hehe this is what i just did :smile:
