### ISSUE TITLE
How to start nvim without starting rust-tools

### ISSUE THREAD

**Issue by elferherrera** [simrat39/rust-tools.nvim#156]
Thanks a lot for your work. It is amazing how good your plugin works with nvim.

My issue is more a question rather that a bug. Is it possible to start nvim without starting `rust-tools`? 
sometimes I want to quickly browse a project without having to check for types or file

What configuration do you suggest for `rust-tools`?

**Comment by simrat39** [comment]
Not sure if you can start with the plugin disabled, but doing a :LspStop should pretty much disable the lsp and all of rust tools. Or you could do nvim --clean (IIRC)

**Comment by YuanYuYuan** [comment]
@elferherrera , you can turn it off by placing this snippet in your vim config.

https://github.com/YuanYuYuan/dotfiles/blob/main/nvim/.config/nvim/lua/plugins/lsp.lua#L178-L184

**Comment by elferherrera** [comment]
@YuanYuYuan thanks for that. It does what I want. Thank you. But now I cannot start the server. I tried with LspStart and nothing. Is there something missing?

**Comment by YuanYuYuan** [comment]
Hi @elferherrera, I just confirmed my config is able to launch the `rust-analyzer` typing in `:LspStart`. My neovim is 0.7.0, which can be [easily installed](https://github.com/YuanYuYuan/dotfiles/tree/main/nvim#option-2-build-from-source) if you wish. Maybe you can check my [config](https://github.com/YuanYuYuan/dotfiles/tree/main/nvim/.config/nvim) to see if there is any difference from yours.

**Comment by elferherrera** [comment]
I have been copying a lot of things from your config :)
I installed `fidget` plugin which tells me when the service has started. I don't see it start after doing LspStart. Probably it only does it when vim starts
