### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by matklad** [simrat39/rust-tools.nvim#16]
Thanks for building this, looks really impressive!

Consider adding a link to this plugin to https://rust-analyzer.github.io/manual.html#nvim-lsp.

**Comment by simrat39** [comment]
Thanks! Love your work on rust-analyzer itself.
https://github.com/simrat39/rust-tools.nvim/issues/16

**Comment by simrat39** [comment]
Wrong repo lmao https://github.com/rust-analyzer/rust-analyzer/pull/8935
