### ISSUE TITLE
Inlay hints does not work on Windows

### ISSUE THREAD

**Issue by MAE-BK201** [simrat39/rust-tools.nvim#170]
I have tested the same configuration for windows with wsl2 and the inlay hints do not work. I am using the `windows version` of neovim from the release page in contrast to the `appimage`.
Configuration:

```lua 
use "simrat39/rust-tools.nvim"
use "neovim/nvim-lspconfig"

require("rust-tools").setup({})
```
Windows:
```shell
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

WSL2 Ubuntu:
```bash
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
Any fixes for this? Would prefer to continue using the Win version of neovim.

**Comment by lucypero** [comment]
Inlay hints don't show up for me, either. I have no idea why. Everything else works great. But I am on a pure WSL2 setup (wsl directory, using all linux programs like linux nvim and linux rust-analyzer). I don't know what's going on. :(

**Comment by simrat39** [comment]
Try and update both your rust analyser and plugins

**Comment by lucypero** [comment]
> Try and update both your rust analyser and plugins

I just tried that. Still doesn't work.

I just compiled `rust-analyzer` from source. and i updated all plugins. I am on pure WSL2. Should act the exact same as linux. What could be the problem?

@simrat39

**Comment by lucypero** [comment]
nvim version
```
:version
NVIM v0.7.0-dev+1341-g79dcd045d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Ws
trict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsu
ggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOUR
CE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/ne
ovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az243-580

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
  ```

**Comment by MAE-BK201** [comment]
I'm very new to the nvim/vim community with that being said, @lucypero do you get the commands that come with rust-tools for e.g `:RustSetInlayHints`?

**Comment by lucypero** [comment]
> I'm very new to the nvim/vim community with that being said, @lucypero do you get the commands that come with rust-tools for e.g `:RustSetInlayHints`?

yes. that one in particular doesn't do anything, though.

**Comment by yil3** [comment]
![图片](https://user-images.githubusercontent.com/57053484/164680950-caabf02b-c349-41e3-a7cb-73a277ff8bb9.png)

#### Debian is equally ineffective

Linux version 5.10.0-13-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.106-1 (2022-03-17)

**Comment by tami5** [comment]
> > I'm very new to the nvim/vim community with that being said, @lucypero do you get the commands that come with rust-tools for e.g `:RustSetInlayHints`?
> 
> yes. that one in particular doesn't do anything, though.

from logs

```rust
[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(I32(120)), method: "textDocument/inlayHint", ...'

```

**Comment by simrat39** [comment]
Due to rust-analyzer changes, please update it to the latest version (and the plugin as well) and see if the issue persists

**Comment by MAE-BK201** [comment]
@simrat39 updating rust-analyzer and rust-tools fixed this issue. P.S if having trouble installing rust-analyzer from source try updating cargo 😉

**Comment by tami5** [comment]
my current version is `rust-analyzer 24cf95762 2022-04-24 dev`and still can't get it to work, very odd, even no logs, I need to debug
