### ISSUE TITLE
`rust-tools` not found

### ISSUE THREAD

**Issue by TornaxO7** [simrat39/rust-tools.nvim#172]
I'm getting the following error message
![image](https://user-images.githubusercontent.com/50843046/163648986-5028f813-ca12-49dd-904e-905114f32b0d.png)

## Reproduction steps

`init.lua`
```lua
packer.startup(function(use)
    use 'wbthomason/packer.nvim'

    use 'nvim-lua/plenary.nvim'

    use {
        'neovim/nvim-lspconfig',
        opt = true,
        cmd = "LspStart",
        requires = {
            {'nvim-lua/lsp-status.nvim'},
            {'folke/lsp-colors.nvim'},
            {'kosayoda/nvim-lightbulb'},
            {'jubnzv/virtual-types.nvim'},
            {'simrat39/rust-tools.nvim'},
        },
        config = function() require("lsp_settings.settings") end
    }
```

`lua/lsp_settings/settings.lua`
```lua
require("rust-tools").setup()
```

Now create a new project `cargo new rofl` and enter the `main.rs` file and execute the command: `:LspStart`, then the error should pop up.

**Comment by TornaxO7** [comment]
Is it possible to use `rust-tools` in lazy mode of `lsp-config`?

**Comment by simrat39** [comment]
Not really a rust-tools issue afaik, looks like something to do with your packer usage, although I won't recommend using it in lazy mode

**Comment by EvanCarroll** [comment]
Just out of curiosity, do you have a keybinding anywhere like this,

> vim.api.nvim_buf_set_keymap(bufnr, 'n', '<Leader>t',  "<cmd>lua require('rust-tools.inlay_hints').toggle_inlay_hints()<CR>", opts)

And does that keybinding not have `bufnr` defined wherever it is used?

**Comment by EvanCarroll** [comment]
I'm getting this error too. All I have to do to get it is,

> `luado require('rust-tools').toggle_inlay_hints()`

```rust
E5111: Error calling lua: [string ":luado"]:1: module 'rust-tools' not found:                                                                        
        no field package.preload['rust-tools']
        no file './rust-tools.lua'
        no file '/usr/share/luajit-2.1.0-beta3/rust-tools.lua'
        no file '/usr/local/share/lua/5.1/rust-tools.lua'
        no file '/usr/local/share/lua/5.1/rust-tools/init.lua'
        no file '/usr/share/lua/5.1/rust-tools.lua'
        no file '/usr/share/lua/5.1/rust-tools/init.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rust-tools.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rust-tools/init.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rust-tools.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rust-tools/init.lua'
        no file './rust-tools.so'
        no file '/usr/local/lib/lua/5.1/rust-tools.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/rust-tools.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/rust-tools.so'
stack traceback:E5111: Error calling lua: [string ":luado"]:1: module 'rust-tools' not found:                                                                        
        no field package.preload['rust-tools']
        no file './rust-tools.lua'
        no file '/usr/share/luajit-2.1.0-beta3/rust-tools.lua'
        no file '/usr/local/share/lua/5.1/rust-tools.lua'
        no file '/usr/local/share/lua/5.1/rust-tools/init.lua'
        no file '/usr/share/lua/5.1/rust-tools.lua'
        no file '/usr/share/lua/5.1/rust-tools/init.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rust-tools.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/rust-tools/init.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rust-tools.lua'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/rust-tools/init.lua'
        no file './rust-tools.so'
        no file '/usr/local/lib/lua/5.1/rust-tools.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/rust-tools.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/ecarroll/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/rust-tools.so'
stack traceback:
        [C]: in function 'require'
        [string ":luado"]:1: in function <[string ":luado"]:1>
        [C]: in function 'require'
        [string ":luado"]:1: in function <[string ":luado"]:1>
```

**Comment by mr-pascal** [comment]
Having the same issue. Also on my side `require('rust-tools').setup({})` triggers some errors.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/4190798/174427777-e0b82eed-2f99-43bc-9ad7-975a061e71ae.png">

Below my `init.vim` and `init.lua`


`init.lua`:
```lua
require('rust-tools').setup({})
```


`init.vim`:
```vim
:set number

:set relativenumber

:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4

:set mouse=a

call plug#begin('~/.config/nvim/plugged')

Plug 'http://github.com/tpope/vim-surround' " Surrounding ysw)
Plug 'https://github.com/preservim/nerdtree' " NerdTree
Plug 'https://github.com/tpope/vim-commentary' " For Commenting gcc & gc
Plug 'https://github.com/vim-airline/vim-airline' " Status bar
Plug 'https://github.com/ap/vim-css-color' " CSS Color Preview
Plug 'https://github.com/rafi/awesome-vim-colorschemes' " Retro Scheme
Plug 'https://github.com/ryanoasis/vim-devicons' " Developer Icons
Plug 'https://github.com/neoclide/coc.nvim'  " Auto Completion
Plug 'https://github.com/tc50cal/vim-terminal' " Vim Terminal
Plug 'https://github.com/terryma/vim-multiple-cursors' " CTRL + N for multiple cursors

" Rust specifics
Plug 'neovim/nvim-lspconfig'
Plug 'simrat39/rust-tools.nvim'

" Rust specifics Debugging
Plug 'nvim-lua/plenary.nvim'
Plug 'mfussenegger/nvim-dap'

set encoding=UTF-8

call plug#end()
nnoremap <C-f> :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>

" no idea what this one does
:set completeopt-=preview " For No Previews

:colorscheme jellybeans

inoremap <expr> <Tab> pumvisible() ? coc#_select_confirm() : "<Tab>"
```

**Comment by TornaxO7** [comment]
hm... it looks like that we have to load the lspconfig first, before rust-tools.nvim can kick in?
I added the following command, which I just execute, if I need it:
```vim
command! LspRustTools lua require('rust-tools').setup({}); require("lsp_settings.keybindings")(0)
```

**Comment by mr-pascal** [comment]
@TornaxO7 
thanks in advance for your help and sorry for the very late reply.
Unfortunately, there seems to be a typo in the code snippet you provide. Sorry if I can't spot it, if it's obvious, unfortunately, I have never written a single LoC in Lua before, so I don't know the syntax.

but when I use your LoC in my Lua config I get the following error:
![image](https://user-images.githubusercontent.com/4190798/177051663-f58a289c-8b5d-4069-927e-6c334e80d7dc.png)

**Comment by simrat39** [comment]
> Having the same issue. Also on my side `require('rust-tools').setup({})` triggers some errors. <img alt="image" width="844" src="https://user-images.githubusercontent.com/4190798/174427777-e0b82eed-2f99-43bc-9ad7-975a061e71ae.png">
> 
> Below my `init.vim` and `init.lua`
> 
> `init.lua`:
> 
> ```lua
> require('rust-tools').setup({})
> ```
> 
> `init.vim`:
> 
> ```viml
> :set number
> 
> :set relativenumber
> 
> :set autoindent
> :set tabstop=4
> :set shiftwidth=4
> :set smarttab
> :set softtabstop=4
> 
> :set mouse=a
> 
> call plug#begin('~/.config/nvim/plugged')
> 
> Plug 'http://github.com/tpope/vim-surround' " Surrounding ysw)
> Plug 'https://github.com/preservim/nerdtree' " NerdTree
> Plug 'https://github.com/tpope/vim-commentary' " For Commenting gcc & gc
> Plug 'https://github.com/vim-airline/vim-airline' " Status bar
> Plug 'https://github.com/ap/vim-css-color' " CSS Color Preview
> Plug 'https://github.com/rafi/awesome-vim-colorschemes' " Retro Scheme
> Plug 'https://github.com/ryanoasis/vim-devicons' " Developer Icons
> Plug 'https://github.com/neoclide/coc.nvim'  " Auto Completion
> Plug 'https://github.com/tc50cal/vim-terminal' " Vim Terminal
> Plug 'https://github.com/terryma/vim-multiple-cursors' " CTRL + N for multiple cursors
> 
> " Rust specifics
> Plug 'neovim/nvim-lspconfig'
> Plug 'simrat39/rust-tools.nvim'
> 
> " Rust specifics Debugging
> Plug 'nvim-lua/plenary.nvim'
> Plug 'mfussenegger/nvim-dap'
> 
> set encoding=UTF-8
> 
> call plug#end()
> nnoremap <C-f> :NERDTreeFocus<CR>
> nnoremap <C-n> :NERDTree<CR>
> nnoremap <C-t> :NERDTreeToggle<CR>
> 
> " no idea what this one does
> :set completeopt-=preview " For No Previews
> 
> :colorscheme jellybeans
> 
> inoremap <expr> <Tab> pumvisible() ? coc#_select_confirm() : "<Tab>"
> ```

Pretty sure init.lua is called before init.vim? so packer doesn't load rust-tools and it can't find it

**Comment by simrat39** [comment]
> hm... it looks like that we have to load the lspconfig first, before rust-tools.nvim can kick in? I added the following command, which I just execute, if I need it:
> 
> ```viml
> command! LspRustTools lua require('rust-tools').setup({})
> ```

nope :), please don't call lspconfig's rust setup as rust-tools also does it and it might cause conflict

**Comment by sarahschwengel** [comment]
Error message:
```
Error detected while processing /home/sarah/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1026: /home/sarah/.config/nvim/lua/plugins.lua:11: module 'rust-tools' not found:
        no field package.preload['rust-tools']
        no file './rust-tools.lua'
        no file '/usr/share/luajit-2.1.0-beta3/rust-tools.lua'
        no file '/usr/local/share/lua/5.1/rust-tools.lua'
        no file '/usr/local/share/lua/5.1/rust-tools/init.lua'
        no file '/usr/share/lua/5.1/rust-tools.lua'
        no file '/usr/share/lua/5.1/rust-tools/init.lua'
        no file './rust-tools.so'
        no file '/usr/local/lib/lua/5.1/rust-tools.so'
        no file '/usr/lib/lua/5.1/rust-tools.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1026: in function <...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:992>
        [C]: in function 'require'
        /home/sarah/.config/nvim/init.lua:4: in main chunk
Press ENTER or type command to continue
```

.config/lua/plugins.lua
```lua
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
-- vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'
  use 'simrat39/rust-tools.nvim'
  
  local rt = require("rust-tools")

end)
```

.config/nvim/init.lua
```lua
-- sarah@bedevere

-- include plugins
use = lua require('plugins')

local impatient_ok, impatient = pcall(require, "impatient")
if impatient_ok then impatient.enable_profile() end

for _, source in ipairs {
  "core.utils",
  "core.options",
  "core.bootstrap",
  "core.plugins",
  "core.diagnostics",
  "core.autocmds",
  "core.mappings",
  "configs.which-key-register",
} do
  local status_ok, fault = pcall(require, source)
  if not status_ok then vim.api.nvim_err_writeln("Failed to load " .. source .. "\n\n" .. fault) end
end

astronvim.conditional_func(astronvim.user_plugin_opts("polish", nil, false))

if vim.fn.has "nvim-0.8" ~= 1 or vim.version().prerelease then
  vim.schedule(function() astronvim.notify("Unsupported Neovim Version! Please check the requirements", "error") end)
end
```

**Comment by AinTEAsports** [comment]
I had the same problem, I just removed `ft = "rust"` from my plugins.lua (for rust-tools config)
Here is before ```rs
use {
    'simrat39/rust-tools.nvim',
    ft = "rust",
    requires = {"neovim/nvim-lspconfig"}
}
```
Here is after, now it's fixed and I no longer have errors about "rust-tools" not being found ```rs
use {
    'simrat39/rust-tools.nvim',
    requires = {"neovim/nvim-lspconfig"}
}
```

**Comment by AinTEAsports** [comment]
I had the same problem, I just removed `ft = "rust"` from my plugins.lua (for rust-tools config)
Here is before
```rust
use {
    "simrat39/rust-tools.nvim",
    ft = "rust",
    requires = {"neovim/nvim-lspconfig"}
}
```
And here is after
```rust
use {
    "simrat39/rust-tools.nvim",
    requires = {"neovim/nvim-lspconfig"}
}
```
And now I don't have any errors about `rust-tools` not being found (I don't know why there was an error but now it works)

**Comment by TornaxO7** [comment]
Damn, I forgot this issue. I don't have this problem anymore either so I think that I can close this issue.
