### ISSUE TITLE
Auto import elements to scope

### ISSUE THREAD

**Issue by daniellga** [simrat39/rust-tools.nvim#181]
Hi! I don't know if this is the right place to ask, but Is there a way to import automatically some element when it gives this error below? Something similar to quick fix in vscode.

```
cannot find derive macro `Component` in this scope
consider importing one of these items:
bevy::ecs::component::Component
crate::Component
```
Thank you!

**Comment by simrat39** [comment]
I believe you can find the import in the code actions ( `vim.lsp.buf.code_action() `)

**Comment by daniellga** [comment]
Nice! Thank you!
