### ISSUE TITLE
disable setup LSP 

### ISSUE THREAD

**Issue by junnplus** [simrat39/rust-tools.nvim#183]
Thanks a lot for your work.

I wrote a plugin [`nvim-lsp-setup`](https://github.com/junnplus/nvim-lsp-setup) wrapping `nvim-lspconfig` and `nvim-lsp-installer`, 
I try to integrate `rust-tools`, but rust-tools always [setup lsp](https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools.lua#L214) . 
Is it possible to add a config to disable it, to setup via installer?

PS: I have read https://github.com/simrat39/rust-tools.nvim/issues/89

**Comment by simrat39** [comment]
I'm not sure if that's possible as the plugin is closely coupled with nvim-lspconfig. As for the users of your plugin, I think they should just not use it for setting up rust if they want to use rust-tools

**Comment by aryzing** [comment]
Seems that running nvim-lspconfig in catching a few people by surprise, myself included. I had a similar problem to https://github.com/simrat39/rust-tools.nvim/issues/177.

It would be great if rust-tools, depending on what it needs internally, had an API that didn't overwrite a user's call to `lspconfig.rust.setup()`. As it stands, I need to treat it like an exception,

```lua
local servers = {
  "eslint",
  "jsonls",
  "rust_analyzer",
  "sumneko_lua",
  "svelte",
  "tsserver",
  "yamlls",
}

for _, server in pairs(servers) do
  local serverOpts = {
    on_attach = on_attach,
  }

  if server == "rust_analyzer" then
    local ok_rt, rust_tools = pcall(require, "rust-tools") 
    if !ok_rt then
      print("Failed to load rust tools, will set up `rust_analyzer` without `rust-tools`.")
    else
      rust_tools.setup({
        server = serverOpts,
      })
      -- We don't want to call lspconfig.rust_analyzer.setup() when using
      -- rust-tools. See
      -- * https://github.com/simrat39/rust-tools.nvim/issues/183
      -- * https://github.com/simrat39/rust-tools.nvim/issues/177
      goto continue
    end
  end

  lspconfig[server].setup(serverOpts)
  ::continue::
end
```
