### ISSUE TITLE
Random error in lua/rust-tools/inlay_hints.lua line 85

### ISSUE THREAD

**Issue by lucabol** [simrat39/rust-tools.nvim#19]
Hi,
I am randomly getting an error that the parameter to len is 'nil' instead of a string. It seems to happen when I switch from a Rust buffer to a non-rust one.

I will try to give you a better repro if I can. In the meantime perhaps you can check for nil at that point in the code? It seems a good improvement anyhow.

Sorry I can't do it myself but I don't speak Lua and don't want to mess things up.

**Comment by lucabol** [comment]
Here is the exact error:

Error executing vim.schedule lua callback: ...pac/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:85:
 bad argument #1 to 'len' (string expected, got nil)

**Comment by Akeboshiwind** [comment]
I'm having the same issue, although I'm also not able to find a minimal reproduction 😭.

I am able to reproduce it on my own machine pretty regularly though.
I just have to open a rust file, then switch to one in another buffer. Maybe a few times.

Thanks to this I was able to narrow down what the issue is. I made the below modifications to the repo:
```diff
diff --git a/lua/rust-tools/inlay_hints.lua b/lua/rust-tools/inlay_hints.lua
index acf1d46..eb0ff07 100644
--- a/lua/rust-tools/inlay_hints.lua
+++ b/lua/rust-tools/inlay_hints.lua
@@ -70,6 +70,8 @@ local function parseHints(result)
     return map
 end
 
+local count = 0
+
 local function get_handler()
     local opts = config.options.tools.inlay_hints
 
@@ -80,12 +82,20 @@ local function get_handler()
         local ret = parseHints(result)
         local max_len = -1
 
-        for key, _ in pairs(ret) do
+        for key, value in pairs(ret) do
+            print(string.format("count: %s", count))
+            count = count + 1
+            print(string.format("loaded?: %s", vim.api.nvim_buf_is_loaded(bufnr)))
+            print(string.format("key: %s", vim.inspect(key)))
+            print(string.format("value: %s", vim.inspect(value)))
+
             local line = tonumber(key)
-            local current_line_len = string.len(
-                                         vim.api.nvim_buf_get_lines(bufnr, line,
-                                                                    line + 1,
-                                                                    false)[1])
+            print(string.format("line: %s", vim.inspect(line)))
+            local lines = vim.api.nvim_buf_get_lines(bufnr, line, line + 1, false)
+            print(string.format("lines: %s", vim.inspect(lines)))
+            local current_line_len = string.len(lines[1])
+
+
             max_len = math.max(max_len, current_line_len)
         end
```

And got this in my `:messages`:
```
count: 0
loaded?: true
key: "1"
value: { {
    kind = "TypeHint",
    label = "i32"
  } }
line: 1
lines: { "    let x = 1;" }
count: 1
loaded?: true
key: "1"
value: { {
    kind = "TypeHint",
    label = "i32"
  } }
line: 1
lines: { "    let x = 1;" }
count: 2
loaded?: true
key: "1"
value: { {
    kind = "TypeHint",
    label = "i32"
  } }
line: 1
lines: { "    let x = 1;" }
count: 3
loaded?: true
key: "1"
value: { {
    kind = "TypeHint",
    label = "i32"
  } }
line: 1
lines: { "    let x = 1;" }
count: 4
loaded?: true
key: "1"
value: { {
    kind = "TypeHint",
    label = "i32"
  } }
line: 1
lines: { "    let x = 1;" }

count: 5
loaded?: false
key: "1"
value: { {
    kind = "TypeHint",
    label = "i32"
  } }
line: 1
lines: {}
Error executing vim.schedule lua callback: ...m/plugged/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:96: bad argument #1 to 'len' (string expected, got nil)
```

So as you can see at some point the function is called while the buffer is unloaded

**Comment by Akeboshiwind** [comment]
I made this change to the code:
```diff
diff --git a/lua/rust-tools/inlay_hints.lua b/lua/rust-tools/inlay_hints.lua
index acf1d46..bafab10 100644
--- a/lua/rust-tools/inlay_hints.lua
+++ b/lua/rust-tools/inlay_hints.lua
@@ -73,7 +73,20 @@ end
 local function get_handler()
     local opts = config.options.tools.inlay_hints
 
-    return function(_, _, result, _, bufnr, _)
+    local handler = nil
+    handler = function(_, _, result, _, bufnr, _)
+        -- If the buffer isn't ready, delay the call
+        if not vim.api.nvim_buf_is_loaded(bufnr) then
+            vim.defer_fn(function()
+                    print("Delayed!")
+                    if handler ~= nil then
+                        handler(nil, nil, result, nil, bufnr, nil)
+                    end
+                end,
+                100)
+            return
+        end
+
         -- clean it up at first
         M.disable_inlay_hints()
 
@@ -157,6 +170,8 @@ local function get_handler()
             enabled = true
         end
     end
+
+    return handler
 end
 
 function M.toggle_inlay_hints()
```

Which is my first attempt at fixing the issue.
It tests to see if the buffer is loaded and if not it delays the hinting by 100ms.

One problem with it is that `Delayed!` is printed when I'm typing in the buffer.
I'm pretty sure this function is supposed to only be called when these events are called:
`InsertLeave,BufEnter,BufWinEnter,TabEnter,BufWritePost`
None of which include typing in the buffer 🤔.

I'm not sure where this second bug comes from, very confusing.

**Comment by Akeboshiwind** [comment]
I've just noticed that once the server load then the `Delayed!` prompt prints even in non `.rs` buffers.
I'm not sure that's supposed to happen either 🤔

**Comment by simrat39** [comment]
I'll try to reproduce this on my machine, but honestly this is pretty hard to fix without being able to reproduce it

**Comment by tbetcke** [comment]
Hi. I also noticed the error. I sometimes get it if I try to jump around files with Telescope, i.e.

```
:telescope find_files<CR>
```
With fzf I have the same problem

**Comment by Akeboshiwind** [comment]
I was finally able to get a minimal repro. It was really finicky and I have no idea how the below causes what I think the error is.

1. Setup a rust project like so:
```shell
$ cargo new my_project
$ echo "fn main() { let x = 1; }" >> my_project/src/main.rs
$ cp my_project/src/main.rs my_project/src/lib.rs
```
2. Startup neovim with the config below
```shell
$ nvim --noplugin -nu init.vim my_project/src/main.rs my_project/src/lib.rs
```
3. Execute the command: `:buffer main | buffer lib`

<details>
    <summary>init.vim</summary>

```lua
lua << EOF
local cmd = vim.cmd
local fn = vim.fn
local opt = vim.opt


-- >> Auto Install packer.nvim

local install_path = fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
end



-- >> Packer plugins

local pack_root = "/tmp/site"
local pack_path = "/tmp/site/pack"

cmd [[packadd packer.nvim]]
require('packer').startup({
  function()
    use {
      'wbthomason/packer.nvim',
      opt = true,
    }

    use 'neovim/nvim-lspconfig'
    use {
      'simrat39/rust-tools.nvim',
      config = [[require"rust-tools".setup {}]],
    }
  end,
  config = {
    compile_on_sync = true,
    auto_reload_compiled = true,
    package_root = pack_root,
    compile_path = pack_path.."/plugin/compiled.vim",
  },
})

require('packer').sync()
EOF
```

Can someone confirm if the above reproduces the issue for them?

</details>

**Comment by Akeboshiwind** [comment]
From trying to reproduce the issue I have a *rough* idea of what's going on:
1. On `BufEnter` (or `BufWinEnter`) `require"rust-tools.inlay_hints".set_inlay_hints()` is called
2. This runs `vim.api.nvim_buf_get_lines`
3. The buffer isn't loaded yet for some reason, or is in a funny state
4. So `vim.api.nvim_buf_get_lines` returns `nil` (even though it's supposed to return an empty array according to the docs?)

**Comment by simrat39** [comment]
> I was finally able to get a minimal repro. It was really finicky and I have no idea how the below causes what I think the error is.
> 
>     1. Setup a rust project like so:
> 
> 
> ```shell
> $ cargo new my_project
> $ echo "fn main() { let x = 1; }" >> my_project/src/main.rs
> $ cp my_project/src/main.rs my_project/src/lib.rs
> ```
> 
>     1. Startup neovim with the config below
> 
> 
> ```shell
> $ nvim --noplugin -nu init.vim my_project/src/main.rs my_project/src/lib.rs
> ```
> 
>     1. Execute the command: `:buffer main | buffer lib`
> 
> 
> init.vim
> 
> ```lua
> lua << EOF
> local cmd = vim.cmd
> local fn = vim.fn
> local opt = vim.opt
> 
> 
> -- >> Auto Install packer.nvim
> 
> local pack_root = "/tmp/site"
> local pack_path = "/tmp/site/pack"
> local install_path = pack_path..'/packer/opt/packer.nvim'
> 
> if fn.empty(fn.glob(install_path)) > 0 then
>   fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
> end
> 
> 
> 
> -- >> Packer plugins
> 
> opt.packpath = pack_root
> local plugin_path = pack_path.."/site/plugin"
> 
> cmd [[packadd packer.nvim]]
> require('packer').startup({
>   function()
>     use {
>       'wbthomason/packer.nvim',
>       opt = true,
>     }
> 
>     use 'neovim/nvim-lspconfig'
>     use {
>       'simrat39/rust-tools.nvim',
>       config = [[require"rust-tools".setup {}]],
>     }
>   end,
>   config = {
>     compile_on_sync = true,
>     auto_reload_compiled = true,
>     package_root = pack_root,
>     compile_path = plugin_path.."/compiled.vim",
>   },
> })
> 
> require('packer').sync()
> EOF
> ```
> 
> Can someone confirm if the above reproduces the issue for them?

Still can't reproduce with these steps, but i think i have a faint idea on what it could be

**Comment by simrat39** [comment]
@Akeboshiwind can you please try the plugin with this diff?
```

diff --git a/lua/rust-tools/inlay_hints.lua b/lua/rust-tools/inlay_hints.lua
index acf1d46..9a02638 100644
--- a/lua/rust-tools/inlay_hints.lua
+++ b/lua/rust-tools/inlay_hints.lua
@@ -74,6 +74,8 @@ local function get_handler()
     local opts = config.options.tools.inlay_hints
 
     return function(_, _, result, _, bufnr, _)
+        if (vim.api.nvim_get_current_buf() ~= bufnr) then return end;
+
         -- clean it up at first
         M.disable_inlay_hints()
 
@@ -82,21 +84,24 @@ local function get_handler()
 
         for key, _ in pairs(ret) do
             local line = tonumber(key)
-            local current_line_len = string.len(
-                                         vim.api.nvim_buf_get_lines(bufnr, line,
-                                                                    line + 1,
-                                                                    false)[1])
-            max_len = math.max(max_len, current_line_len)
+            local current_line = vim.api.nvim_buf_get_lines(bufnr, line,
+                                                            line + 1, false)[1]
+            if (current_line) then
+                local current_line_len = string.len(current_line)
+                max_len = math.max(max_len, current_line_len)
+            end
         end
 
         for key, value in pairs(ret) do
             local virt_text = ""
             local line = tonumber(key)
 
-            local current_line_len = string.len(
-                                         vim.api.nvim_buf_get_lines(bufnr, line,
-                                                                    line + 1,
-                                                                    false)[1])
+            local current_line = vim.api.nvim_buf_get_lines(bufnr, line,
+                                                            line + 1, false)[1]
+
+            if (not current_line) then goto continue end
+
+            local current_line_len = string.len(current_line)
 
             local param_hints = {}
             local other_hints = {}
@@ -155,6 +160,8 @@ local function get_handler()
 
             -- update state
             enabled = true
+
+            ::continue::
         end
     end
 end

```

**Comment by Akeboshiwind** [comment]
I've tried it out and I'm not unable to reproduce the error 👍

**Comment by Akeboshiwind** [comment]
Thanks 🎉 

Hopefully this is the cause of everyone else's issues too :D

**Comment by tbetcke** [comment]
Thanks for all your effort. Tried it and seems to be working fine now.

**Comment by simrat39** [comment]
Thanks for the reports and the help :)

**Comment by jasonjurotich** [comment]
When runnging :!cargo fmt in neovim, the following comes out below:

`Error executing vim.schedule lua callback: ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:142: Index out of bounds
stack traceback:
        [C]: in function 'nvim_buf_get_lines'
        ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:142: in function 'parse_hints'
        ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:168: in function 'handler'
        ...w/Cellar/neovim/0.9.4/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
`
