### ISSUE TITLE
[Feature] Open docs.rs for an identifier

### ISSUE THREAD

**Issue by crisidev** [simrat39/rust-tools.nvim#193]
First of all thanks for this amazing plugin!

I am trying to achieve this for a while and I did not find a way yet and I am not even sure it is possible given how https://docs.rs search works.

I'd like to be able to open the docs.rs page of an identifier.

Example:

```rust
use http::request::Request;
use http::response::Response;

async fn handler(req: &mut Request) -> Response {
    todo!()
}
```

When I have my curson on `Request` in the async function, I would like to hit something like `:lua require("rust-tools").open_documentation()` and have my browser open https://docs.rs/http/latest/http/request/struct.Request.html.

A bonus would be to be able to go to the right version of the crate instead of just the latest.

Do you think it is something that could be done? I would be happy to contribute, but I am not even sure where to start..

**Comment by ok-nick** [comment]
I was just looking for this feature and wondering why it wasn't implemented in `rust-tools`. It's definitely possible, and it looks like it has been done [here](https://github.com/rhysd/rust-doc.vim) although unmaintained.

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/commit/060463c3a486b8d016be1ec9cd9ed172826586da This should be what you're looking for

**Comment by crisidev** [comment]
Nice! Works perfectly!
