### ISSUE TITLE
RustRunnables run commands under neovim startup dir instead of detected workspace root

### ISSUE THREAD

**Issue by comicfans** [simrat39/rust-tools.nvim#20]
when running a test by RustRunnables, neovim error out

```
error: could not find `Cargo.toml` in '/home/comicfans' or any parent directory
```

but actually LspInfo shows workspace root is 

```
/home/comicfans/some/other/dir
```

**Comment by simrat39** [comment]
Rust analyser gives back a directory (iirc), so I guess we need to cd into it before running the actual command, I'll get it don't today

**Comment by comicfans** [comment]
confirm worked

**Comment by simrat39** [comment]
That's awesome, thanks for reporting!
