### ISSUE TITLE
Warning when using hover action: fancy_floating_markdown is deprecated

### ISSUE THREAD

**Issue by Akeboshiwind** [simrat39/rust-tools.nvim#21]
## Description

When I try to view the documentation for a symbol I get the following error in `:messages`:

```
fancy_floating_markdown is deprecated. Please use open_floating_preview and pass focus_id = [unique_name] instead
```

Here's an example of what I'm seeing:
<img src="https://user-images.githubusercontent.com/8889986/120719964-1f6f8080-c4c3-11eb-8624-97a00cc54dcd.gif" width="500">
(Appologies for the colorscheme and slowness. Default nvim 🤷)

## Steps to reproduce:

Using this config:

<details><summary>init.vim</summary>

```viml
set completeopt=menuone,noselect
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'simrat39/rust-tools.nvim'

call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF

require('rust-tools').setup { }

EOF

nnoremap <silent> K <cmd>lua vim.lsp.buf.hover()<CR>
```

</details>

1. Create a test rust repo: `cargo new my_repo`
2. Open nvim `nvim -nu test.vim my_repo/src/main.rs`
3. Navigate to the `println!` symbol
4. Type `K` to bring up the documentation popup

## Expected:

Shows the window, with no warning messages

## Actual

Shows the warning message

## Additional Details

Nvim version: `v0.5.0-dev+1362-g3cd688ff7`
Plugin commit hash: `6f92ba636c06069592c64f85888b452da7e81cfd`
OS: Mac OS

**Comment by simrat39** [comment]
Thanks for the report!

**Comment by Akeboshiwind** [comment]
Thanks for the quick work ;)
