### ISSUE TITLE
Spawning language server with cmd: `rust-analyzer` failed. The language server is either not installed, missing from PATH, or not executable.

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [simrat39/rust-tools.nvim#214]
I found a little edge case and I am not sure how to solve it. 

Error: 
> Spawning language server with cmd: `rust-analyzer` failed. The language server is either not installed, missing from PATH, or not executable.

My setup:
`rust-analyzer` is in fact NOT in path, BUT is being passed directly to lsp `cmd` attribute as path:
```lua
nvim_lsp.rust_analyzer.setup({
  cmd = [ '/path/to/rust-analzyer']
  ...
}
```

**Comment by jrmoulton** [comment]
I'm not sure how you have the rest of your configs but the problem might be that if you really are using rust-tools you need to pass the config into the rust-tools setup function. 
``` lua
local rust_opts = {
    server = {
        cmd = ['/path/to-rust-analyzer']
    },
}
require('rust-tools').setup(rust_opts)

```

**Comment by simrat39** [comment]
> 

Also please don't call lspconfig's setup, as rust-tools does it automatically and it causes conflicts if called twice
