### ISSUE TITLE
Inlay Hints eventually stop updating after long enough sessions

### ISSUE THREAD

**Issue by dialtone** [simrat39/rust-tools.nvim#216]
Here's a gif of what I mean: 

![gif](https://user-images.githubusercontent.com/23195/178134103-60650f54-e4e7-4491-b7c7-2838c83db842.gif)

It works fine when nvim is just started, but fails afterwards.

You can see the same exact thing [here](https://youtu.be/zmLgbI6hLnM?t=758) if you watch for the next minute or two the streamer just has to reload the workspace to get inlay hints to update.

[this](https://github.com/dialtone/dotfiles/blob/main/.config/nvim/lua/dialtone/plugins/setup.lua) is my setup.

**Comment by simrat39** [comment]
#230
