### ISSUE TITLE
cannot input words into terminal

### ISSUE THREAD

**Issue by Civitasv** [simrat39/rust-tools.nvim#218]
So, I have codes to print any character I input to the terminal. Like:

```rust
fn main() {
    for b in io::stdin().bytes() {
        let c = b.unwrap() as char;
        println!("{}", c);
    }
}
```

**Actual behavior:** But when I run it, the execute terminal won't let me input and it will be closed after whatever key I click.
![image](https://user-images.githubusercontent.com/37768049/178422004-4f53bd47-0895-4f88-a70c-48977f25a4a2.png)

**Expected behavior:** I should be able to input, and when I input `<C-c>`, it will stop.

Any idea?

**Comment by simrat39** [comment]
You can press `i` to go into insert mode in the terminal buffer

**Comment by Civitasv** [comment]
When I press `i`, yes, it enter into insert mode, but then after I input something, it'll disappear. See:
![Peek 2022-07-14 10-29](https://user-images.githubusercontent.com/37768049/178885186-0f211ff1-00b4-4574-9f49-b6afc37f81aa.gif)

**Comment by simrat39** [comment]
Looks like the process exits (successfully as well). For some reason, it isn't waiting for your input.

Could you test this code out?

`fn main() {
    loop {
        let mut a = String::new();
        io::stdin().read_line(&mut a);
        println!("{}", a)
    }
}
`

**Comment by Civitasv** [comment]
I find it weird. I think it enters into loop and wait for my input in the terminal.
But I can't input anything in it(and you can see I've entered into terminal mode from normal mode). After click `Ctrl+C`, it exits.

![Peek 2022-07-14 13-15](https://user-images.githubusercontent.com/37768049/178904655-9a8b0ca3-ea46-4201-bc97-9584b98655bd.gif)

You can see my [config](https://github.com/Civitasv/runvim/blob/master/lua/user/rust.lua) for rust-tools.

**Comment by simrat39** [comment]
Don't think this is an issue with rust-tools, but with your terminal. What happens if you run the code outside of neovim? Does the issue still persist?
