### ISSUE TITLE
The latest version of codelldb requires a explicitly specified port

### ISSUE THREAD

**Issue by ofseed** [simrat39/rust-tools.nvim#223]
![image](https://user-images.githubusercontent.com/61115159/179688369-a89cd61f-2834-40af-ba74-aeaa378cba9c.png)

**Comment by meinside** [comment]
Yes, it works on [v1.6.10](https://github.com/vadimcn/vscode-lldb/releases/tag/v1.6.10), but fails like this since v1.7.x.

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/commit/9e00f62d0bb2aadcaf1b56b0c6a4b67cbb2fe103
Was fixed in a branch which will be merged soon hopefully, so feel free to check it out

**Comment by meinside** [comment]
Branch [modularize_and_inlay_rewrite](https://github.com/simrat39/rust-tools.nvim/tree/modularize_and_inlay_rewrite) fixes this issue. When do you think it will be merged to master?

**Comment by simrat39** [comment]
Fix has been merged
