### ISSUE TITLE
turn off treesitter in hover window

### ISSUE THREAD

**Issue by elianiva** [simrat39/rust-tools.nvim#23]
I noticed that the hover window treats the entire content as Rust because I believe it uses Treesitter for the entire hover window. Is it possible to turn it off? Ideally it would be great if it only inject TS inside the codeblock but I think TS can only work on buffer level.

with rust-tools:

![image](https://user-images.githubusercontent.com/51877647/121102871-d869ee00-c828-11eb-8f78-ddfc694b20e8.png)

without rust-tools: 

![image](https://user-images.githubusercontent.com/51877647/121102893-e28bec80-c828-11eb-8d7b-99986865ae59.png)

**Comment by simrat39** [comment]
The filetype is set to rust for better highlighting, hopefully the new preview api improves on the highlighting so I'll see that and remove the filetype on the hover window (or set it to markdown)

**Comment by simrat39** [comment]
So, the thing is that we get markdown text from the language server, parse it and then show it in a buffer, highlight that buffer and then show it to the user. The highlighting part is done by the open_floating_preview api, which applies highlights over a certain range of lines. Now whenever there are actions, we append to the buffer which causes everything to shift down and messes up the highlighting. To prevent this, we enabled tree-sitter inside the buffer to get pseudo-decent highlighting, but a proper fix would be to apply the highlights AFTER adding the actions, this would require a complete re-implementation of the floating preview api. So, for now we'll just enable tree sitter on hovers which have actions

**Comment by elianiva** [comment]
That sounds good to me, thanks!
