### ISSUE TITLE
Inlay hints eventually fail and require lsp server restart

### ISSUE THREAD

**Issue by erikkrieg** [simrat39/rust-tools.nvim#230]
After working on a project for a couple hours I have found on multiple occasions that inlay hints stop appearing. When I check `:LspLog` I see errors like the following:

```
[ERROR][2022-08-08 01:08:56] .../vim/lsp/rpc.lua:420  "rpc" "rust-analyzer" "stderr"  "::inlay_hints::inlay_hints
   4: std::panicking::try
   5: ide::Analysis::inlay_hints
   6: rust_analyzer::handlers::handle_inlay_hints
   7: std::panicking::try
   8: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace."
```

I have been able to resolve this when it occurs by running `:LspRestart`, though I would expect to not need to do this, ofc.

I have experienced this with the basic setup of the plugin, `require('rust-tools').setup({})`

Versions I am using:
- rustc 1.61.0 (fe5b13d68 2022-05-18)
- rust-analyzer 0.0.0 (897a7ec4b 2022-07-17)
- rust-tools (11dcd674781ba68a951ab4c7b740553cae8fe671)
- NVIM v0.7.2

**Comment by dialtone** [comment]
I reported the same thing here: https://github.com/simrat39/rust-tools.nvim/issues/216
In my case a `:LspRestart` isn't enough to have them appear, and I have the same backtraces in `:LspLog`.

I end up in cases like [this](https://imgur.com/5FDNJL5)

**Comment by simrat39** [comment]
Interesting, looks like something is happening over at rust analyser. Is there any other confirmed reproduction other than editing for a long time? Maybe a large amount of files or something like that?

**Comment by augustocdias** [comment]
Not sure if it is the same issue, but after updating this morning I'm having this error:

```
Error executing vim.schedule lua callback: ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:196: line value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:196: in function 'render_line'
        ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:226: in function 'render'
        ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:140: in function 'handler'
        ...neovim/HEAD-7ebcb9b_1/share/nvim/runtime/lua/vim/lsp.lua:1241: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by dialtone** [comment]
> Interesting, looks like something is happening over at rust analyser. Is there any other confirmed reproduction other than editing for a long time? Maybe a large amount of files or something like that?

I can reproduce it right away after starting, no need to edit for a long time. The last video I posted shows me restarting nvim and displays the issue.

**Comment by erikkrieg** [comment]
> Interesting, looks like something is happening over at rust analyser. Is there any other confirmed reproduction other than editing for a long time? Maybe a large amount of files or something like that?

For me it was with a very small project in terms of my own source code (I am using a few crates, tho).

**Comment by simrat39** [comment]
Should be fixed with https://github.com/simrat39/rust-tools.nvim/commit/2e9e47372930e66541a70b865fea167947b4d1da

**Comment by simrat39** [comment]
> Not sure if it is the same issue, but after updating this morning I'm having this error:
> 
> ```
> Error executing vim.schedule lua callback: ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:196: line value outside range
> stack traceback:
>         [C]: in function 'nvim_buf_set_extmark'
>         ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:196: in function 'render_line'
>         ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:226: in function 'render'
>         ...acker/opt/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:140: in function 'handler'
>         ...neovim/HEAD-7ebcb9b_1/share/nvim/runtime/lua/vim/lsp.lua:1241: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>
> ```

This should also be fixed, though its a bandaid fix for now, not sure why ra is sending a line which doesn't exist

**Comment by erikkrieg** [comment]
Thanks, @simrat39!

**Comment by dialtone** [comment]
Beautiful, it works! :)

thanks!
