### ISSUE TITLE
Standalone file support

### ISSUE THREAD

**Issue by emi2k01** [simrat39/rust-tools.nvim#25]
I wonder if standalone file support [1] could be supported with this plugin or if that's the work of another plugin like lsp-config.

[1]: https://github.com/rust-analyzer/rust-analyzer/pull/8955

**Comment by runiq** [comment]
Support for that may be a little preliminary at the moment: For now, the list of files r-a considers standalone has to be supplied at LSP server start. This implies a LSP server restart whenever a new standalone file is being opened in a buffer.

This behavior is subject to change soon, but for now it is what it is :shrug:

**Comment by simrat39** [comment]
This works as expected but please let me know if there any problems, it might be a bit wonky

**Comment by simrat39** [comment]
As of now, the language server will start automatically if you open a rust file directly (nvim abc.rs), but you can manually start it for a buffer with the `RustStartStandaloneServerForBuffer` command.

**Comment by p00f** [comment]
Is it just me or are the default lsp handlers used instead of the overriden ones on standalone files? (hover, diagnostics)

**Comment by simrat39** [comment]
@p00f can you try again now? it seems to work fine for me

**Comment by p00f** [comment]
Yes, thanks

**Comment by emi2k01** [comment]
It seems `on_attach` is not called when I run `RustStartStandaloneServerForBuffer`
