### ISSUE TITLE
How to use floating windows when :RustRunnables?

### ISSUE THREAD

**Issue by MrZLeo** [simrat39/rust-tools.nvim#250]
When I try to type `:RustRunnables`, I only get a terminal windows below the screen:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/25260092/188271329-6b78e682-5482-4062-8513-872176be484a.png">

But in the demo:

![](https://github.com/simrat39/rust-tools-demos/raw/master/runnables.gif)

I can see a floating windows here. I am new in neovim-lsp things, so I want to know how this work? How I can get that?

![image](https://user-images.githubusercontent.com/25260092/188271382-cf45a8a1-94a9-4974-ad75-b2d486463208.png)

**Comment by MrZLeo** [comment]
I try this configuration:

```lua
local opts = {
    tools = { -- rust-tools options
        executor = require("rust-tools/executors").termopen,
        runnables = {
            use_telescope = true
        },
... -- other things
}

but it didn't work.

**Comment by hawkinchina** [comment]
@MrZLeo how it works ?   i get the same question.

**Comment by MrZLeo** [comment]
> @MrZLeo how it works ? i get the same question.

you will need to use other plugin like [dressing](https://github.com/stevearc/dressing.nvim) to achieve this feature.

**Comment by hawkinchina** [comment]
hi, man,  thanks a lot. it works.
