### ISSUE TITLE
Many native lsp features are not their

### ISSUE THREAD

**Issue by ayush-india** [simrat39/rust-tools.nvim#263]
Many of the native lsp features are not their in rust-tools eg:

        vim.lsp.buf.declaration()
        vim.lsp.buf.definition()
        vim.lsp.buf.signature_help()
        vim.lsp.buf.type_definition()
        vim.lsp.buf.references()
        vim.diagnostic.goto_prev()
        vim.diagnostic.goto_next()
        vim.diagnostic.setloclist()
        vim.lsp.buf.implementation()
and if their are these features the please tell me how can i use them because the insctructions are not clear 

Thanks for reading

**Comment by Diablo-D3** [comment]
This seems like a bug better filed with the nvim-lsp team.

**Comment by ayush-india** [comment]
I will try to fix it on my own by removing rust-tools and trying to do only with rust lsp 

I will keep updating

**Comment by ayush-india** [comment]
I got it working 

Let me know if anyone wants the config

**Comment by ayush-india** [comment]
Just remove rust tools and use native lsp instead to get more features
