### ISSUE TITLE
where to configure the path of rust-analyzer?

### ISSUE THREAD

**Issue by vimalk78** [simrat39/rust-tools.nvim#265]
I plan to use https://github.com/pr2502/ra-multiplex/, since it can keep rust-analyzer runing in the background.

So i need to change the path of the executable used by this plugin.

i want `rust-tools` to use `ra-multiplex` instead of `rust-analyzer` directly.

  where do i change it?

**Comment by korsmakolnikov** [comment]
up +

**Comment by blkgoose** [comment]
I've looked around the code, one can change the `cmd` as such:
``` lua
    use {
        'simrat39/rust-tools.nvim',
        config = function()
            require('rust-tools').setup {
                server = {
                    cmd = { "ra-multiplex" }
                }
            }
        end,
    }
```

This won't work though, `ra-multiplex` will give an error saying `duplicate DidOpenTextDocument`, thus the issue cannot be resolved here but only on neovim's internal LSP.

**Comment by xbladesub** [comment]
same problem. How to specify path? I used rustup to install rust-analyzer

**Comment by xbladesub** [comment]
in my case it worked with 
```
	server = {
		cmd = { "/Users/nshv/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rust-analyzer" },
```

**Comment by simrat39** [comment]
Put it in config.server.cmd and make sure you're not setting up rust analyzer separately through lspconfig as rust-tools already does that
