### ISSUE TITLE
Incorrect syntax in inlay_hints.lua

### ISSUE THREAD

**Issue by Kannen** [simrat39/rust-tools.nvim#27]
When I try to use this pluggin and run
"require('rust-tools').setup(opts)" as specficied in the readme file I get error:

inlay_hints.lua:102: '=' expected near 'continue'

I am using neovim 0.5.0 and lua version is 5.1

**Comment by simrat39** [comment]
It works fine for me. Can you please post your nvim --version ?

**Comment by Kannen** [comment]
```
NVIM v0.5.0
Build type: Gentoo
Lua 5.1
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=haswell -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-0.5.0/work/neovim-0.5.0_build/config -I/var/tmp/portage/app-editors/neovim-0.5.0/work/neovim-0.5.0/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.5.0/work/neovim-0.5.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.5.0/work/neovim-0.5.0_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by Kannen** [comment]
If I replace:
```
if (not current_line) then goto continue end
...
::continue::
```
by:
```
if current_line then
...
end
```
The error disappear. It behaves as if `goto` was not supported...

**Comment by simrat39** [comment]
@Kannen For some reason, your build does not come with luajit (i think?). Anyways, the goto keyword was added in Lua 5.2 so that's why its not supported on your build. I'll probably change it so it works but it shouldn't ideally be like that

**Comment by simrat39** [comment]
btw luajit supports the goto statement even though its based on lua 5.1
https://www.reddit.com/r/lua/comments/zzkwb/luajit_now_supports_goto_using_the_lua_52_syntax/
