### ISSUE TITLE
Hover Doc maximum width and height

### ISSUE THREAD

**Issue by Ritzier** [simrat39/rust-tools.nvim#274]
How to set hove_doc maximum width and height, my hover doc window is look too big

![Fri Oct 28 04:12:22 PM +08 2022](https://user-images.githubusercontent.com/85002404/198538382-51b621ab-4bcc-4a9a-ae90-6209d7276820.png)

**Comment by simrat39** [comment]
config.tools.hover_actions.max_{width/height}
