### ISSUE TITLE
 /imports/granularity/group: unknown variant `last`, expected one of `preserve`, `item`, `crate`, `module`

### ISSUE THREAD

**Issue by winkee01** [simrat39/rust-tools.nvim#275]
Hello, when I open a *.rs file, I encountered this error.
```
LSP[rust_analyzer][Warning] rust-analyzer found 1 invalid config value:
/imports/granularity/group: unknown variant `last`, expected one of `preserve`, `item`, `crate`, `module`
LSP[rust_analyzer][Warning] rust-analyzer found 1 invalid config value:
/imports/granularity/group: unknown variant `last`, expected one of `preserve`, `item`, `crate`, `module`
```

<img width="979" alt="CleanShot 2022-10-29 at 13 46 56@2x" src="https://user-images.githubusercontent.com/49930785/198816046-89cb5dac-d7a4-4c3b-9464-486112f8b0ff.png">

**Comment by simrat39** [comment]
What's your rust-tools setup, nvim version and rust-analyzer version?

**Comment by winkee01** [comment]
I pull the lastest commit and the error suddenly disappeared.
