### ISSUE TITLE
Set cargo features

### ISSUE THREAD

**Issue by TornaxO7** [simrat39/rust-tools.nvim#283]
Hello! I'm trying to add some parameters to the `features` list but I can't get it working. This is currently how I'm calling up rust-tools:
```lua
	require("rust-tools").setup({
		server = {
			on_attach = on_attach,
			capabilities = capabilities,
			standalone = true,
			cargo = {
				features = { "test" },
			},
		},
	})
```
do you have an idea what I'm doing wrong?

**Comment by TornaxO7** [comment]
Found a workaround with [neoconf](https://github.com/folke/neoconf.nvim).

**Comment by TornaxO7** [comment]
jj

**Comment by xiqqsec** [comment]
I am having the same problem, same configuration
