### ISSUE TITLE
`RustExpand` does not work

### ISSUE THREAD

**Issue by segeljakt** [simrat39/rust-tools.nvim#284]
I get: `error: Unrecognized option: 'pretty'`

**Comment by segeljakt** [comment]
`:lua require'rust-tools'.expand_macro.expand_macro()` seems to work though

**Comment by simrat39** [comment]
the command is `RustExpandMacro`, not sure where `RustExpand` is coming from

**Comment by segeljakt** [comment]
Ok, currently, the readme says RustExpandMacro

**Comment by Jasha10** [comment]
It turns out that `:RustExpand` is built-in to Neovim.
https://github.com/neovim/neovim/blob/8c9dab3e0d788d44c8a2fee83a6193f5955c814e/runtime/ftplugin/rust.vim#L120
