### ISSUE TITLE
rust inlay_hints render bug

### ISSUE THREAD

**Issue by Meigumikato** [simrat39/rust-tools.nvim#311]
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/49133741/210959347-ee480c1d-380b-42ca-8cb2-d8bcce9d837d.png">

system: macOS 13.1
neovim: NVIM v0.8.2

**Comment by eatgrass** [comment]
same problem
rust-analyzer version: 2023-01-02

**Comment by Meigumikato** [comment]
// code snippet
#[derive(Debug)]
enum Color {
    Black,
    Blue,
    Brown,
    Custom(String),
    Gray,
    Green,
    Purple,
    Red,
    White,
    Yellow,
}


#[derive(Debug)]
struct ShoesColor(Color);
impl ShoesColor {
    fn new(c: Color) -> Self {
        Self(c)
    }
}

#[derive(Debug)]
struct ShirtColor(Color);
impl ShirtColor {
    fn new(c: Color) -> Self {
        Self(c)
    }
}

#[derive(Debug)]
struct PantsColor(Color);
impl PantsColor {
    fn new(c: Color) -> Self {
        Self(c)
    }
}


fn print_clothe_color(c : Color) {
    println!("{:?}", c)
}

fn main() {
    let shoes = ShoesColor::new(Color::Red);  // <- edit on this line after will trigger this bug
}

**Comment by MichaelMandel26** [comment]
Duplicate of #300

**Comment by FrankReh** [comment]
I'll second that the #307 PR fixes the problem.

**Comment by Meigumikato** [comment]
thanks

**Comment by MichaelMandel26** [comment]
@FrankReh I have replaced the plugin in my config with the fork from kdarkhan and it works good for me :)
