### ISSUE TITLE
How to set `rust-analyzer.cargo.target`?

### ISSUE THREAD

**Issue by jjant** [simrat39/rust-tools.nvim#321]
Hi, I have a mixed native/wasm32-unknown-unknown project and `#[cfg(target_arch = "wasm32")]` blocks don't get analyzed.

[Apparently you can set a `rust-analyzer.cargo.target` option for this](https://github.com/rust-lang/rust-analyzer/issues/5904) but I don't see an easy way to do it with `rust-tools` (ideally based on my project's `Cargo.toml` or `.cargo/config`).
Any ideas on how I can achieve this?

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/wiki/Server-Configuration-Schema
