### ISSUE TITLE
No compilation artifacts found

### ISSUE THREAD

**Issue by sufar** [simrat39/rust-tools.nvim#324]
## My configurations

```
require("mason").setup()
require("mason-lspconfig").setup()

local mason_home = vim.fn.stdpath "data" .. "/mason"

require("mason-lspconfig").setup_handlers {
  function(server_name)
    require("lspconfig")[server_name].setup {}
  end,
  ["rust_analyzer"] = function()
    require("rust-tools").setup({
      dap = {
        adapter = require('rust-tools.dap').get_codelldb_adapter(
          mason_home .. "/packages/codelldb/extension/adapter/codelldb",
          mason_home .. "/packages/codelldb/extension/lldb/lib/liblldb.so")
      }
    })
    require('crates').setup()
  end,
}

```

## Problem: No compilation artifacts found
:RustDebuggables test can not work because of this **commit 5a2f7e9c127cec00be2201d6aa262f96155bdd23**

![image](https://user-images.githubusercontent.com/82210712/215236970-0c56090c-7e60-4a02-9e85-6a2c378e7c87.png)
![image](https://user-images.githubusercontent.com/82210712/215236986-77ee2ffb-f3e9-4c48-93b6-2c727fc099f7.png)

error: No compilation artifacts found

## Reset to fix

```
cd ~/.local/share/nvim/site/pack/packer/start/rust-tools.nvim
git reset --hard df584e84393ef255f5b8cbd709677d6a3a5bf42f
```

It works well:
![image](https://user-images.githubusercontent.com/82210712/215237108-b4921ff8-1e7d-48bf-951a-84bb0bdbffff.png)

**Comment by simrat39** [comment]
Fixed in #327
