### ISSUE TITLE
Option to disable LSP highlighting

### ISSUE THREAD

**Issue by mkeeter** [simrat39/rust-tools.nvim#365]
Good morning!  I've noticed a regression after updating to neovim 0.9.

A few seconds after startup, it switches from treesitter to LSP highlighting, which is worse (it doesn't correctly highlight docstrings or TODO):

Treesitter
<img width="598" alt="Screenshot 2023-04-12 at 9 00 47 AM" src="https://user-images.githubusercontent.com/745333/231465651-9e9f14db-ab79-4a1a-9c13-02ead9ef3452.png">

LSP
<img width="608" alt="Screenshot 2023-04-12 at 9 00 59 AM" src="https://user-images.githubusercontent.com/745333/231465687-96b7139a-9dd8-407d-973c-e1c563c780c9.png">

I attempted to disable this with 
```lua
      local rt = require'rust-tools'

      rt.config.options.server.capabilities.textDocument.semanticTokens = vim.NIL
      rt.config.options.server.capabilities.workspace.semanticTokens = vim.NIL
```
in my configuration, but it didn't seem to work.

Any suggestions on how to disable LSP highlighting?

**Comment by mkeeter** [comment]
Ah, I finally found the right setting:
```lua
      vim.api.nvim_set_hl(0, '@lsp.type.comment.rust', {})
```
This will disable LSP highlighting in Rust comments.

(`:help lsp-semantic-highlight` for more details)

I'm not sure if `rust-tools` wants to do this by default, but it was definitely a surprising change in behavior for me!

**Comment by PSeitz** [comment]
I got the same issue, and this is how to disable it completely.

```lua
  local rt = require("rust-tools")

  rt.setup({
    server = {
      on_attach = function(client, bufnr)
        client.server_capabilities.semanticTokensProvider = nil
        -- Hover actions
        vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
        -- Code action groups
        vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
      end,
    },
  })

```

**Comment by bleczz** [comment]
I just moved on from vimscript and coc to lua and lsp along with treesitter and I've been debugging for two days because this was driving me insaaaane! Thanks a lot for the hint. 

A simple way to disable it completely for every file so only treesitter's highlight is applied would be setting this into your init.lua:

```
for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
        vim.api.nvim_set_hl(0, group, {})
end
```

**Comment by DieracDelta** [comment]
@bleczz is this working or you on neovim 0.9.0? `:highlight` is showing all the `@lsp` highlight groups as cleared. But I'm still faced with semantic tokens. Any ideas? I'm getting stuff like:
![image](https://user-images.githubusercontent.com/13730968/234989568-0c3a3086-f64b-4669-ad60-a4ede3046121.png)

**Comment by bleczz** [comment]
Hi, @DieracDelta. I'm on `NVIM v0.10.0-dev`

**Comment by DieracDelta** [comment]
@bleczz which rev?

**Comment by simrat39** [comment]
Seems like this is LSP semantic highlighting, so it should be on by default, and can be disabled in the ways said above
