### ISSUE TITLE
Client exited with code 1

### ISSUE THREAD

**Issue by Ziothh** [simrat39/rust-tools.nvim#377]
Hi I'm really enjoying the tooling you've built.

As of late the rust tools log this error when entering a `.rs` file:
<img width="395" alt="Screenshot 2023-05-02 at 22 40 33" src="https://user-images.githubusercontent.com/81878355/235780942-22762bd6-2809-4051-a4cd-a97936f9e748.png">

This causes the whole toolchain to stop working.
I can't find the problem in my config so out of desperation I'm opening this issue.
Any idea what I'm doing wrong?

Thanks in advance!

I'm using NvChad. 
My config in ~/.config/nvim/lua/custom/: https://github.com/Ziothh/nvim/tree/main

**Comment by utkarshgupta137** [comment]
You should look at the logs at `~/.local/state/nvim/lsp.log`.

**Comment by Ziothh** [comment]
Thanks for the tip @utkarshgupta137!
I have installed rust-analyzer with Mason. 
It's fixed by running `rustup component add rust-analyzer`.

The error being logged:
`[ERROR][2023-05-02 22:40:20] .../vim/lsp/rpc.lua:733	"rpc"	"rust-analyzer"	"stderr"	"'rust-analyzer' is not installed for the toolchain 'stable-aarch64-apple-darwin'"`
