### ISSUE TITLE
Add option to disable setting up rust_analyzer

### ISSUE THREAD

**Issue by dstanberry** [simrat39/rust-tools.nvim#38]
Super nit-picky request, but would you consider adding an optional parameter to prevent calling `setup_lsp()`?

**Comment by simrat39** [comment]
But why though? Thus plugin is extremely integrated with rust analyzer, and won't work without it. If you want to add your own stuff while setting up ra you can do so by passing it in the server options. The plugin also makes a lot of changes to the capabilities / lsp handlers for better integration, which would cause a few features to not work

**Comment by dstanberry** [comment]
Totally fair point - I should've added my reasoning as well, again just my preference here.. I like having all the `require('lspconfig').server.setup(...)` in a for loop so as to not have a bunch of nearly identical chunks

```lua
local servers = {
,,,
}
for _, server in ipairs(servers) do
  lspconfig[server].setup(config)
end
```

I already have a short-circuit for rust_analyzer and would prefer not to have another for rust_tools. Not the end of the world if you decide against the request, just thought it was worth asking.

**Comment by simrat39** [comment]
Yeah im not too big on having this, it will only hinder your experience
