### ISSUE TITLE
hover_actions: Show actions  inside the actual hover dialog?

### ISSUE THREAD

**Issue by simrat39** [simrat39/rust-tools.nvim#4]

**Comment by simrat39** [comment]
![image](https://user-images.githubusercontent.com/37233846/113933176-1acf6a00-97a9-11eb-8dac-88b86e7248c1.png)
:thinking:

**Comment by simrat39** [comment]
https://github.com/simrat39/rust-tools.nvim/commit/3b440ccf2c4684369c61ab72f712e9c3c1a0b00d

**Comment by winkee01** [comment]
hello, I can see the hover action, but how I can perform the action? I press <Enter>, but it doesn't work.
<img width="859" alt="CleanShot 2022-10-10 at 12 05 22@2x" src="https://user-images.githubusercontent.com/49930785/194797932-e09411d6-fe9d-483e-ab2f-2a7f90cdfa8d.png">

**Comment by kertkukk** [comment]
Okay but from where to you set `auto_focus = true`?
