### ISSUE TITLE
Docs: Show how this plugin can be used with other LSPs

### ISSUE THREAD

**Issue by hunger** [simrat39/rust-tools.nvim#42]
I want to set up not only rust support in nvim but also other LSPs for bash, go, clangd, etc.

Considering that this plugin will interact with `lsp-config`: How do I configure those LSP servers without breaking the rust support?

Some documentation on how to configure such a setup would be appreciated.

**Comment by simrat39** [comment]
Just setup your other servers normally. The plugin doesn't mess with those.

```lua
require'lspconfig'.tsserver.setup {capabilities = capabilities}
-- other servers
require'rust-tools'.setup({
    server = {
        on_attach = on_attach,
    }
})
```

**Comment by hunger** [comment]
Thanks, I will try that.
