### ISSUE TITLE
Passing "on_attach" does not work as expected

### ISSUE THREAD

**Issue by cinerea0** [simrat39/rust-tools.nvim#43]
I have configured other language servers to automatically attach to buffers using a line like so:

```
require'lspconfig'.pylsp.setup({ on_attach=on_attach })
```

However, using a similar configuration for rust-tools does not result in the language server automatically attaching to Rust buffers. Here is the relevant configuration:

```lua
local on_attach = function(client)
  require'completion'.on_attach(client)
end

require('rust-tools').setup({
  server = { on_attach = on_attach }
})
```

**Comment by simrat39** [comment]
This works fine for me. Can you put a print statement in your on attach function and see if it prints that?

**Comment by cinerea0** [comment]
Placing a print statement in that function does result in in being printed out. I guess the problem is that, despite the function being called, the lsp doesn't actually activate. Could this be a result of how I've structured my files, or should that not matter?

**Comment by simrat39** [comment]
If on_attach is being called then the lsp is running and being attached to the buffer. You can run :LspInfo to confirm that. Btw, why don't you try nvim-compe? I think most people use that and you don't need to pass it around in the on_attachs of your language server configs.

**Comment by cinerea0** [comment]
Switching to nvim-compe fixed the issue of hints not actually showing up. However, despite setting `autoSetHints = true`, I have to manually invoke `:RustSetInlayHints` in order for them to show up.

**Comment by simrat39** [comment]
@cinerea0 lol how did compe fix the hints, anyways that should only happen when you open the editor, but I have a fix for it now that I think about it, meanwhile you can :w after a second and the hints will show up, or switch to another buffer.

**Comment by cinerea0** [comment]
Hey, just wanted to let you know that the hints are showing up. Thank you!
