### ISSUE TITLE
generate default code when converting #[derive(Debug)] to a manual implementation doesn't work

### ISSUE THREAD

**Issue by lowstar** [simrat39/rust-tools.nvim#53]
RA since release 2021-08-09 (https://rust-analyzer.github.io/thisweek/2021/08/09/changelog-89.html) generates default code when converting #[derive(Debug)] to manual impl. Since version 2021-08-16 (https://rust-analyzer.github.io/thisweek/2021/08/16/changelog-90.html) this functionality was extended to other derive macros (namely Default, Hash, Clone or PartialEq). This works fine in vscode but doesn't work in nvim with rust-tools.nvim. Codeaction 'Convert to manual `impl std::fmt::Debug for ...` generates only empty impl without `fmt` method itself.

Tested with latest RA installed via homebrew on macOS>

```
% rust-analyzer --version
rust-analyzer 996300f4a 2021-08-23 dev
```

**Comment by simrat39** [comment]
Output should be the same regardless of neovim or vscode, could be something with nvim's lsp client, I'll have to take a look. But for now you can do s code actions on the impl and generate the missing methods.

**Comment by lowstar** [comment]
It almost works:

```rust
#[derive(Debug)]
struct Foo {
    value: u32,
}
```

After calling "Convert to manual ..." code action, I get this:

```rust
struct Foo {
    value: u32,
}

impl std::fmt::Debug for Foo {
    $0fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Foo").field("value", &self.value).finish()
    }
}
```

That `$0` in front of `fn` seems strange ...
