### ISSUE TITLE
lldb-vscode not found - despite lldb being installed

### ISSUE THREAD

**Issue by badrbouslikhin** [simrat39/rust-tools.nvim#54]
Hello,

I cannot use `RustDebuggables` because `lldb-vscode not found. Please install lldb.`
I am on macOS 11.5.1 and lldb is installed through `xcode` with `xcode-select --install`.

What am I missing?

Thanks!

**Comment by simrat39** [comment]
> Hello,
> 
> I cannot use `RustDebuggables` because `lldb-vscode not found. Please install lldb.`
> I am on macOS 11.5.1 and lldb is installed through `xcode` with `xcode-select --install`.
> 
> What am I missing?
> 
> Thanks!

You just need lldb-vscode in your path, i'm not too familiar with mac os but you might want to look into vscode-lldb installation instructions for mac os

**Comment by badrbouslikhin** [comment]
Thanks! It's added. The error changed to and is now `Error on launch: process launch failed: unable to locate debugserver`. Is there another dependency that needs to be installed and added to my path?

<img width="1391" alt="Screenshot 2021-08-30 at 10 14 46" src="https://user-images.githubusercontent.com/7818591/131308248-c5b8055a-2fe0-4ce6-91f7-daa7c55ad65b.png">
<img width="1391" alt="Screenshot 2021-08-30 at 10 15 09" src="https://user-images.githubusercontent.com/7818591/131308251-7c011054-45e3-4096-93a1-99d513ede7fd.png">

**Comment by ca-mantis-shrimp** [comment]
agreed,

I'm able to successfully run lldb-vscode from the CLI by using `lldb-vscode-11` pictured below:

![image](https://user-images.githubusercontent.com/25948785/131769324-90060054-182d-40ea-bdc9-1f558c6ca631.png)

but i'm still getting the above error when I try to run `RustDebuggables`?

**Comment by simrat39** [comment]
Honestly, I can't really help here because I don't have a mac device. Would it be possible for you guys to setup https://github.com/mfussenegger/nvim-dap and then help me with the steps so I can put it in the plugin? rust-tools uses nvim-dap in the background so if you get dap working externally then the plugin will also work fine

**Comment by simrat39** [comment]
Also this might be a shot in the dark, but could you try to replace https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools/dap.lua#L7 with lldb-server?

**Comment by ca-mantis-shrimp** [comment]
Just to note,

I'm on WSL for Windows, not Mac, idk if that says anything.

**Comment by simrat39** [comment]
> Just to note,
> 
> I'm on WSL for Windows, not Mac, idk if that says anything.

rust-tools looks for `lldb-vscode` in your path, but you seem to have `lldb-vscode-11` so I think you should try changing the binary name here https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools/dap.lua#L7 and if it works then we can add a config to change the binary name

**Comment by wonbyte** [comment]
> > Just to note,
> > I'm on WSL for Windows, not Mac, idk if that says anything.
> 
> rust-tools looks for `lldb-vscode` in your path, but you seem to have `lldb-vscode-11` so I think you should try changing the binary name here https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools/dap.lua#L7 and if it works then we can add a config to change the binary name

I was looking at the binary  vscode extension CodeLLDB pulls down and it seems to name it ‘lldb’. Having a config to change the name would be great!

**Comment by wonbyte** [comment]
@simrat39 Thanks for the configuration option :)

**Comment by simrat39** [comment]
Does this work now? Let me know and I'll close the issue

**Comment by simrat39** [comment]
Ok so i'll be closing this, here's the fix for mac os if anyone is interested:

Download the CodeLLDB vscode extension
Get the lldb-server binary from there
Change the adapter settings of rust-tools to point to that binary

**Comment by badrbouslikhin** [comment]
Thanks for the update!
I still have trouble using the plugin.
Here's my config:
```
-- rust-tools configuration
local opts = {
    dap = {
        adapter = {
            type = 'executable',
            command = 'lldb-vscode',
            name = "rt_lldb"
        }
    }
}
require('rust-tools').setup(opts)
```
This leads to:
`Error on launch: process launch failed: unable to locate debugserver`

When changing command to `lldb-server`:
```
-- rust-tools configuration
local opts = {
    dap = {
        adapter = {
            type = 'executable',
            command = 'lldb-server',
            name = "rt_lldb"
        }
    }
}
require('rust-tools').setup(opts)
```
I get:
`Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `rt_lldb` configuration. Check the logs for errors (:help dap.set_log_level)`

**Comment by simrat39** [comment]
> Thanks for the update! I still have trouble using the plugin. Here's my config:
> 
> ```
> -- rust-tools configuration
> local opts = {
>     dap = {
>         adapter = {
>             type = 'executable',
>             command = 'lldb-vscode',
>             name = "rt_lldb"
>         }
>     }
> }
> require('rust-tools').setup(opts)
> ```
> 
> This leads to: `Error on launch: process launch failed: unable to locate debugserver`
> 
> When changing command to `lldb-server`:
> 
> ```
> -- rust-tools configuration
> local opts = {
>     dap = {
>         adapter = {
>             type = 'executable',
>             command = 'lldb-server',
>             name = "rt_lldb"
>         }
>     }
> }
> require('rust-tools').setup(opts)
> ```
> 
> I get: `Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `rt_lldb` configuration. Check the logs for errors (:help dap.set_log_level)`

I'm sorry, i gave you the wrong instructions.
Try this: https://github.com/simrat39/rust-tools.nvim#a-better-debugging-experience and let us know!

**Comment by badrbouslikhin** [comment]
Thanks for the doc. update @simrat39.
I still have an issue:
`Error executing vim.schedule lua callback: /Users/badr/.config/nvim/plugged/nvim-dap/lua/dap.lua:658: Adapter used with attach must have a port property`
Also on my install, there's no `.so`:
```
vadimcn.vscode-lldb-1.6.7/lldb/lib 
❯ l
.rwxr-xr-x badr staff  71 MB Sun Oct  3 12:50:07 2021 - liblldb.dylib
.rwxr-xr-x badr staff 9.7 MB Sun Oct  3 12:50:07 2021 - libpython39.dylib
drwxr-xr-x badr staff 128 B  Sun Oct  3 12:50:07 2021 - lldb-python
drwxr-xr-x badr staff 6.2 KB Sun Oct  3 12:50:07 2021 - python3.9
```

**Comment by simrat39** [comment]
> Thanks for the doc. update @simrat39. I still have an issue: `Error executing vim.schedule lua callback: /Users/badr/.config/nvim/plugged/nvim-dap/lua/dap.lua:658: Adapter used with attach must have a port property` Also on my install, there's no `.so`:
> 
> ```
> vadimcn.vscode-lldb-1.6.7/lldb/lib 
> ❯ l
> .rwxr-xr-x badr staff  71 MB Sun Oct  3 12:50:07 2021 - liblldb.dylib
> .rwxr-xr-x badr staff 9.7 MB Sun Oct  3 12:50:07 2021 - libpython39.dylib
> drwxr-xr-x badr staff 128 B  Sun Oct  3 12:50:07 2021 - lldb-python
> drwxr-xr-x badr staff 6.2 KB Sun Oct  3 12:50:07 2021 - python3.9
> ```

The .dylib should also be fine. Looks like the port isnt being set, this is probably because your codelldb adapter is a bit slow to startup. I can fix that issue. But could you please run the codelldb binary from the command line and show what it outputs?

**Comment by simrat39** [comment]
Should be fixed now, idk why gihub closes the issue
