### ISSUE TITLE
LSP only starts after editing a file twice

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [simrat39/rust-tools.nvim#57]
Hello,

I'm using the default configuration found on the main github page within my rust.lua file. 

However, for some reason the LSP only attaches after I enter another buffer (usually the same file), after which `LspInfo` correctly shows it as being attached to the rust analyzer.

Is this a configuration ordering problem? the plugin isn't broken, but having to open a file twice to get LSP started is getting old. especially when you mix that with the fact that inlay hints don't always leave after I solve the problem and it makes for a cumbersome experience.

Don't get me wrong, I LOVE your plugin and this is more of an annoyance than a show-stopping bug, but i'm just having trouble understanding how such strange behavior could be happening. if this is an lspconfig thing I can bring it over there because it seems that MOST of rust-tools work before I edit the file a second time, it just doesn't show the inlay hints and inlay types until I actually get it all configured.

Thank you for your hard work and any time or knowledge you may have on this subject.

**Comment by simrat39** [comment]
> I'm able to verify that there are no agents attached to the buffer on first open through 'LspInfo' and the agent appears after editing at least once.
> 
> Should I maybe put this in a before/ folder so it runs before normal LSP startup?

Do you have this with vanilla rust-analyzer+lspconfig (no rust-tools) as well? Also probably unrelated but are you setting up rust_analyzer and rust-tools together by any chance?

**Comment by ca-mantis-shrimp** [comment]
So at first, I had rust_analyzer configured with lsp-config, but I wanted to make the transition clean, so I took the rust analyzer config OUT of my general LSP-config. 

I am calling rust-tools within my rust.lua file located in the ftplugin folder.

When it was setup with lsp-config, I would need to safe to get diagnostics, but I DID have an attached agent, even if the diagnostics don't show up, and they would show up after a simple write.

Now I only get this attached after I re-open `e file.rs` before the agent is attached. then diagnostics still take a second, but I want to focus on the agent not being attached on first buffer open.

Thank you for your patience and expertise.

**Comment by simrat39** [comment]
> So at first, I had rust_analyzer configured with lsp-config, but I wanted to make the transition clean, so I took the rust analyzer config OUT of my general LSP-config.
> 
> I am calling rust-tools within my rust.lua file located in the ftplugin folder.
> 
> When it was setup with lsp-config, I would need to safe to get diagnostics, but I DID have an attached agent, even if the diagnostics don't show up, and they would show up after a simple write.
> 
> Now I only get this attached after I re-open `e file.rs` before the agent is attached. then diagnostics still take a second, but I want to focus on the agent not being attached on first buffer open.
> 
> Thank you for your patience and expertise.

Please move the rust-tools setup out of ftplugin and into init.lua (or any file required/sourced by init.lua). Rust tools sets up some autocommands which wont run at first if you have it in the ftplugin folder.

**Comment by ca-mantis-shrimp** [comment]
> Please move the rust-tools setup out of ftplugin and into init.lua (or any file required/sourced by init.lua). Rust tools sets up some autocommands which wont run at first if you have it in the ftplugin folder.

Okay, this is a fine workaround and I appreciate you telling me. But is there a way to run these kinds of files automatically? It seems strange that autocommands don't run in ftplugin automatically. 

You can close this of there is no other way
