### ISSUE TITLE
require('rust-tools').setup({}) clobbers on_attach

### ISSUE THREAD

**Issue by goolord** [simrat39/rust-tools.nvim#59]
i have a custom `on_attach` function configured for rust-analyzer which does not fire when rust-tools is installed. i think this is a bad user experience, i want to be able to do things like set keybindings in buffers where a language server has started

**Comment by darthdeus** [comment]
Did you figure out how to set this up? I just ran into the same exact issue trying out `rust-tools.nvim`

**Comment by simrat39** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/37233846/131233643-69c9292f-2e35-46bf-aa99-57bb2579417b.png)
![image](https://user-images.githubusercontent.com/37233846/131233648-7ffd2d6e-3e69-4278-bec0-2bc7eb461d8d.png)

**Comment by simrat39** [comment]
Make sure you put it in the server table inside the options

**Comment by goolord** [comment]
ah so that's what's meant by
> This plugin automatically sets up nvim-lspconfig for rust_analyzer for you

you don't need to call `lspconfig.rust_analyzer.setup`

thank you
