### ISSUE TITLE
DAP debugging not working

### ISSUE THREAD

**Issue by wonbyte** [simrat39/rust-tools.nvim#63]
This is most likely a user error but hoping you have some insight. I’m running Arch on an old T410 and when I just start a bare bones cargo project ‘cargo new —lib foo’. I’m not able to debug the initial unit test. Essentially nothing happens at all. Is there a way I can debug to get more info?

I have all the requirements met and you can see my configs here: https://github.com/wonbyte/.dotfiles/tree/main/.config/nvim

I’m also running ‘terminator’ as my terminal

**Comment by simrat39** [comment]
Are you setting a breakpoint?

**Comment by wonbyte** [comment]
Yep, I just get a message “Compiling a debug build for debugging. This may take some time…” but nothing ever happens

**Comment by wonbyte** [comment]
Nm, total user error. I didn’t realize dap ui was a separate package and got confused based on README screenshot.
