### ISSUE TITLE
Optional handler for Runnables and Debuggables commands

### ISSUE THREAD

**Issue by augustocdias** [simrat39/rust-tools.nvim#64]
Would it be possible to have an optional parameter in the `runnables` and `debuggables` so I could pass my own handler in case I don't use telescope but use something else?

**Comment by simrat39** [comment]
> Would it be possible to have an optional parameter in the `runnables` and `debuggables` so I could pass my own handler in case I don't use telescope but use something else?

Not really possible, you would have to write all the code which is pretty redundant. But this will change in the future, see https://github.com/neovim/neovim/pull/15202
