### ISSUE TITLE
No configuration found for rust. You need to add configs to dap.configurations.rust

### ISSUE THREAD

**Issue by wonbyte** [simrat39/rust-tools.nvim#67]
It seems like after having the `dap` configuration added, debugging no longer works out of the box for me. Every-time I try to debug I get the a No configuration found for `rust`. I would expect it should find your default config if I did not override it.

<img width="1680" alt="Screen Shot 2021-09-24 at 10 28 30" src="https://user-images.githubusercontent.com/681965/134701335-5f5453ca-3311-40fe-bee7-1b0cdd5b318c.png">

**Comment by wonbyte** [comment]
Unless this is the new default behavior where we are now providing our own configs?

**Comment by simrat39** [comment]
Mhm it shouldn't be like this. It should behave the old way. What is your rust-tools config?

**Comment by wonbyte** [comment]
This is what i currently have: https://github.com/wonbyte/.dotfiles/blob/main/nvim/.config/nvim/lua/lsp/init.lua#L39

But i have also tried it with just `require('rust-tools').setup({})` and still encounter the issue.

**Comment by simrat39** [comment]
And you're using the hover actions menu to enter debugging?

**Comment by wonbyte** [comment]
🤦 I'm an idiot... It's working fine, sorry about that.

**Comment by simrat39** [comment]
lol no worries, feel free to close the issue
