### ISSUE TITLE
LSP[rust_analyzer] rust-analyzer failed to load workspace: Failed to parse edition 2021

### ISSUE THREAD

**Issue by thorlucas** [simrat39/rust-tools.nvim#69]
I installed `rust-tools` and added the default setup to my lua files. I commented out all other lspconfig related setups to avoid intereference.

I upgraded everything using rustup.

```
   stable-x86_64-apple-darwin unchanged - rustc 1.55.0 (c8dfcfe04 2021-09-06)
  nightly-x86_64-apple-darwin unchanged - rustc 1.57.0-nightly (05044c2e6 2021-09-26)
```

I ran `cargo new playground && cd playground`

I opened neovim.

I get the error:

```
LSP[rust_analyzer] rust-analyzer failed to load workspace:
Failed to read Cargo metadata from Cargo.toml file xxx/playground/Cargo.toml, cargo 1.57.0-nightly (0121d66aa 2021-09-22): 
Failed to parse edition 2021: invalid edition: "2021"
```

Why?

**Comment by simrat39** [comment]
This is probably a rust-analyzer issue. Try updating your rust-analyzer and see if it works now. Also check if i works with vscode/lspconfig's rust-analyzer setup.

**Comment by thorlucas** [comment]
You're right -- uninstalling RA and reinstalling the `rust-analyzer-preview` via rustup and telling LSP to use that binary seems to have worked.

**Comment by erikpols** [comment]
>> You can pass a custom cmd to the server settings, you can see how to do it in the lspconfig repo
sorry- I have this problem but I dont understand this. Could you elaborate?

**Comment by thorlucas** [comment]
> > > You can pass a custom cmd to the server settings, you can see how to do it in the lspconfig repo
> 
> sorry- I have this problem but I dont understand this. Could you elaborate?

I am on mobile so I can’t give you more detailed info right now, but in rust tools config there is a key which allows you to pass a table to the LSP’s config.  LSP’s config has a key named “cmd” which specifies which command is run when starting the language server. Just change that command to reflect the preview binary.
