### ISSUE TITLE
How to support snippets on code actions expansions.

### ISSUE THREAD

**Issue by emi2k01** [simrat39/rust-tools.nvim#74]
If I have the following code:

```rs
pub struct Foo;

impl std::fmt::Display for Foo {
}

fn main() {
}
```

and I use the code action `Implement missing members`, the generated code is:

```rs
pub struct Foo;

impl std::fmt::Display for Foo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ${0:todo!()} // I want my cursor to move here.
    }
}

fn main() {
}

```

I am using vim-vsnip for regular snippets.

I don't know if this is in the scope of rust-tools or not.

**Comment by emi2k01** [comment]
It makes sense. Should this issue be closed? I'll keep an eye on the vim-snip issue.

Thanks!

**Comment by simrat39** [comment]
Let's keep it open for now

**Comment by hrsh7th** [comment]
I think rust-tools.nvim should get the snippet expansion function as a configuration item. (nvim-cmp does it).

And You can override the `vim.lsp.util.apply_text_edits` function. (I don't like this solution but I have no another idea...

**Comment by sharksforarms** [comment]
I would expect it to work like this where you can configure how the snippet gets expanded: https://github.com/hrsh7th/nvim-cmp/blob/main/README.md?plain=1#L70-L81

**Comment by ModProg** [comment]
I don't know if this is related, but when using rust_analyzer with lspconfig without rust-tools I get this expansion on "fill match arms":
```rs
match c {
    Test::A(_) => todo!(),
    Test::B(_) => todo!(),
    Test::C { a, b, c } => todo!(),
}
```

But with rust-tools this happens:
```rs
match c {
    Test::A(${0:_}) => todo!(),
    Test::B(_) => todo!(),
    Test::C { a, b, c } => todo!(),
}
```

Maybe it is possible to have the lspconfig expansion for now, until the cursor move is implemented, as that code is at least compilable?

**Comment by Freyskeyd** [comment]
I agree for now I can't really use rust-tools for that :s
Can we have an option to switch from one another ?

**Comment by simrat39** [comment]
Fixed with https://github.com/simrat39/rust-tools.nvim/commit/01904961647c44a4111a856e5afd5aa83ce19621
