### ISSUE TITLE
debug single test actually run all tests

### ISSUE THREAD

**Issue by ryanhuanli** [simrat39/rust-tools.nvim#76]
I noticed all tests running when I only debugging one,  traced rust-tools and found args.executableArgs (which specify testname) is not passed to dap.

This is what get it working locally, not sure if this is on-purpose for some other reason or simply missed:

lua/rust-tools/dap.lua:125

![image](https://user-images.githubusercontent.com/329310/137052185-2f0fbfc2-b330-4fd4-8f45-6c1fa82e355f.png)

**Comment by simrat39** [comment]
Yes this is something that was missed, ill fix it later or you can open a pull request
