### ISSUE TITLE
[BUG] Getting error on the latest commit

### ISSUE THREAD

**Issue by druskus20** [simrat39/rust-tools.nvim#79]
Im getting the following error on the latest commit: e3b0ace51db01e6fbecae489645b911a8f4b3441
```
packer.nvim: Error running config for nvim-lspconfig: ...packer/start/rust
-tools.nvim/lua/rust-tools/commands.lua:12: attempt to index field 'comman
ds' (a nil value)
```
Tried restoring rust-tools to ec6028323cc9cd37187eccb7ffdc5bab8c249d08 and it works

**Comment by TornaxO7** [comment]
The same happens for me.

**Comment by simrat39** [comment]
Should be fixed now lol

**Comment by simrat39** [comment]
Let me know if its not because I don't want to switch back to 0.5.1 again for such  a small fix

**Comment by TornaxO7** [comment]
Fixed for me as well. Thanks!
