### ISSUE TITLE
Not an editor command: RustRunnables

### ISSUE THREAD

**Issue by tomleavy** [simrat39/rust-tools.nvim#81]
I'm not sure why I get this error, everything else seems to work fine?

**Comment by simrat39** [comment]
Nope, still does nothing. Try it in a cargo project

**Comment by tomleavy** [comment]
Just to be clear, none of the commands seem to work, but the plug-in itself is loaded because rust-analyzer works and I can see type annotations etc. 

I feel like I'm missing something in terms of how these commands are supposed to become available?

**Comment by tomleavy** [comment]
I'm just running nvim from the root directory of the cargo project

**Comment by Avimitin** [comment]
I got a same issue too. I can only use ":lua require("rust-tools.hover_actions").hove_actions()" to call the command "RustHoverActions". I can't found any rust-tools vim command in the prompt.

**Comment by Avimitin** [comment]
Here is how I load rust-tools.nvim: https://github.com/Avimitin/nvim/blob/master/lua/plug.lua#L102
Here is how I set the lsp: https://github.com/Avimitin/nvim/blob/master/lua/config/lsp.lua#L104-L132
And here is my rust-tools.nvim configuration: https://github.com/Avimitin/nvim/blob/master/lua/config/rust.lua

**Comment by TornaxO7** [comment]
I remember that I had them once, but now they are missing

**Comment by simrat39** [comment]
Can't reproduce with latest neovim and rust-analyzer, could you please post your versions?

**Comment by Avimitin** [comment]
Mine: NVIM v0.6.0-dev+501-gcb15055c2

**Comment by mbpowers** [comment]
@Elabajaba Where is the cache file located? I have removed all mentions of rust_analyzer from my config and uninstalled from nvim-lsp-installer with no luck.

**Comment by Elabajaba** [comment]
I don't remember if I had to run PackerClean in neovim, or if it was from actually deleting the file on disk.

On Windows it's somewhere in C:\Users\YOURUSERNAME\AppData\Local\nvim-data\ (%localappdata% to get there easily). On linux, I think it's somewhere in  ~/.local/share/nvim/

**Comment by mbpowers** [comment]
Hmmm it seems that the files in .local/share/nvim/ were deleted upon uninstall through nvim-lsp-installer. Not sure how to proceed.
