### ISSUE TITLE
Disable `Press ENTER or type command to continue` when saving a Cargo.toml

### ISSUE THREAD

**Issue by oblique** [simrat39/rust-tools.nvim#88]
When I save a Cargo.toml, nvim pauses and displays `Press ENTER or type command to continue`.

I personally do not like this. Is it ok if I open a PR that removes the `vim.notify("Reloading Cargo Workspace")` which causes this pausing? Another option is to add `silent` on `autocmd BufWritePost`.

**Comment by oblique** [comment]
A 3rd option is to add augroup, so the user will be able to disable it. For example:

```vim
augroup rust_tools
    autocmd BufWritePost */Cargo.toml lua require('rust-tools/workspace_refresh')._reload_workspace_from_cargo_toml()
    au VimEnter *.rs lua require('rust-tools').start_standalone_if_required()
augroup END
```

And someone can add `silent` from their config with:

```vim
autocmd! rust_tools BufWritePost
autocmd BufWritePost */Cargo.toml silent lua require('rust-tools/workspace_refresh')._reload_workspace_from_cargo_toml()
```

**Comment by simrat39** [comment]
Third option sounds good. vim.notify shouldn't show the press enter thingy but idk why its doing that for you

**Comment by oblique** [comment]
I will not open a PR, the following solves the issue:

```lua
vim.opt.cmdheight = 2
```
