### ISSUE TITLE
Options to customize inlay hints

### ISSUE THREAD

**Issue by sharksforarms** [simrat39/rust-tools.nvim#9]
The prefix seems to be hard coded to `=>`. I normally prefer no prefix, would it be possible to make this configurable?

Also, is there a way to disable inlay hints by default? I thought `autoSetHints = false` would do this but it still seems to be added on save

**Comment by simrat39** [comment]
![image](https://user-images.githubusercontent.com/37233846/115091635-e193aa00-9ecc-11eb-9a55-0a1727a076ea.png)
Of course its possible, I'll push this after testing it a bit more
As for the autoSetHints, thats a my bad, i'm checking for opts.autoSetHints not opts.tools.autoSetHints as shown in the docs

**Comment by simrat39** [comment]
local opts = {
    tools = { 
        inlay_hints = {
            -- prefix for parameter hints
            -- default: "<-"
            parameter_hints_prefix = "<-",

            -- prefix for all the other hints (type, chaining)
            -- default: "=>"
            other_hints_prefix  = "=>",
        },
    },

let me know if it works fine so i can close the issue

**Comment by sharksforarms** [comment]
Forgot to reply! This is perfect. Thanks!
