### ISSUE TITLE
cmp-nvim not working reliably

### ISSUE THREAD

**Issue by qdrs** [simrat39/rust-tools.nvim#90]
I have the latest rust toolchain and rust-analyzer / rust-tools seem to have slowed down dramatically.

1) I keep getting overly long loop run errors.
2) Whenever I type out something like `let x = String::` the autocomplete for string doesn't show the methods available on String, however if i backspace twice and then type :: again, it may sometimes show the available methods?

Any help would be appreciated.

Thanks

**Comment by simrat39** [comment]
This is a cmp / lspconfig issue. Please try to reproduce this with lspconfig's rust-analzyer setup then report the issue to the respective repos

**Comment by simrat39** [comment]
Closing because not a rust-tools issue
