### ISSUE TITLE
Output to quickfix

### ISSUE THREAD

**Issue by Shatur** [simrat39/rust-tools.nvim#91]
I would like to suggest to display the output in quickfix directly. Like in https://github.com/skywind3000/asyncrun.vim or https://github.com/Shatur/neovim-cmake.

**Comment by simrat39** [comment]
Thats a good idea, but i think we should have a generic run_command setting so that we can support floatterm and this usecase / more

**Comment by simrat39** [comment]
So i have an alpha version up and running, but I can't get the qflist to parse the errors using 'erroformat', would you have any idea how to do that? cause without it it's kinda useless to have it in the qflist

**Comment by Shatur** [comment]
You probably want to set it to something like this: https://github.com/rust-lang/rust.vim/blob/4aa69b84c8a58fcec6b6dad6fe244b916b1cf830/compiler/rustc.vim#L32
