### ISSUE TITLE
diagnostic windows are focused by navigation actions

### ISSUE THREAD

**Issue by daveriedstra** [simrat39/rust-tools.nvim#99]
I've stumbled on two scenarios where diagnostic windows gain focus when they shouldn't.

First, if the buffer has only one diagnostic, calling `vim.lsp.diagnostic.goto_next()` twice (or followed by `.goto_prev()`) will focus the diagnostic window because the action to show the window has been taken twice.

Second, if `CursorHold` is configured to call `vim.lsp.diagnostic.show_line_diagnostics()`, navigating to a diagnostic with `vim.lsp.diagnostic.goto_next()` (or `.goto_prev()`) will focus the diagnostic window (the navigation immediately triggers the window to open and the `CursorHold` timeout triggers the second action to focus the window).

Both cases are unexpected because the explicit action was navigation to another point in the buffer, not to the diagnostic window.

**Comment by simrat39** [comment]
This is expected neovim behaviour, nothing to do with this plugin. I believe there is a way to turn it off though

**Comment by sharksforarms** [comment]
Is this similar to what you're experiencing? https://github.com/sharksforarms/sharksforarms.github.io/issues/13#issuecomment-974870574

If so,
`vim.lsp.diagnostic.show_line_diagnostics({focusable = false})`

or in 0.6
`vim.diagnostic.open_float(nil, {focusable = false})`

**Comment by simrat39** [comment]
yes!! that should fix it. i was trying to find it but its not documented lol

**Comment by daveriedstra** [comment]
Fantastic, that's exactly it. Thanks @sharksforarms & @simrat39 !
